### ISSUE TITLE
Chips with icon: Icon is not centered

### ISSUE THREAD

**Issue by theunreal** [driftyco/ionic#10354]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Using ion chips with an icon shows the icon in the right side (RTL layout).
![image](https://cloud.githubusercontent.com/assets/6171883/22740614/218f550a-ee19-11e6-8fe1-72db2eaf2acc.png)

**Expected behavior:**
The icon need to be in the center of the chip's circle

**Related code:**

```
<ion-chip color="dark">
                    <ion-icon name="search"></ion-icon>
                    <ion-label>Test</ion-label>
                    </ion-chip>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.9.2
Xcode version: Not installed
```

**Comment by brandyscarney** [comment]
@theunreal Thanks for the issue! Can you try using the latest release:

```
npm install ionic-angular@latest --save --save-exact
```

I am not able to see this problem anymore and we released a fix for icons in chips in that release. :)

**Comment by theunreal** [comment]
Works thanks @brandyscarney

**Comment by alex-pl** [comment]
I'm still facing this issue on an iPad mini 2 with iOS 9.3.5 and an iPhone 5 with iOS 9.3.5.
It works on Android and desktop browsers (like Firefox, Chrome, Safari) via `ionic serve`.

I run the command above and removed the folders www/ platforms/ plugins/. Didn't help.
