### ISSUE TITLE
[rootParams] are 'undefined' when an active tab is selected again

### ISSUE THREAD

**Issue by Grafelhaft** [driftyco/ionic#11308]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
While using the ionic tabs and tab components, the [rootParams] are 'undefined' when the same tab is selected again. When a specific tab is already active and you press it a second time, then the [rootParams] are 'undefined'. Whenever pressing on another tab other than the active one, then the [rootParams] are defined as expected.

**Expected behavior:**
The [rootParams] shouldn't be 'undefined' when a tab is selected again, rather have the same [rootParams] as defined when pressing another tab other than the active one.

**Steps to reproduce:**
Create a new tabs example project with the ionic v3 cli like explained [here](http://blog.ionic.io/ionic-cli-v3-beta/). Run: "ionic start tabsExample tabs"

You can `console.log()` the [rootParams] in the constructors of the tab content pages.

**Related code:**

```
<ion-tabs>
 <ion-tab [root]="home" [rootParams]="'a'" tabTitle="Home" tabIcon="home"></ion-tab>
<ion-tab [root]="about" [rootParams]="'b'" tabTitle="About" tabIcon="information-circle"></ion-tab>
<ion-tab [root]="contact" [rootParams]="'c'" tabTitle="Contact" tabIcon="contacts"></ion-tab>
</ion-tabs>

constructor(public navParams: NavParams) {
   console.log("NavParams", navParams);
}
```

**Other information:**
The [rootParams] are defined, when selecting another tab other than the already selected.

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us. This has been fixed and will be in the next release.

**Comment by zevaxt** [comment]
This problem is still  presented in the version 4.1.0 ionic. Is there any solution or alternative?
