### ISSUE TITLE
<ion-select> fires ionChange event twice

### ISSUE THREAD

**Issue by ciekawy** [driftyco/ionic#11480]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
for `<ion-select (ionChange)="changed($event)">`  the `changed` method is being called twice for each change

**Expected behavior:**

the `(ionChange)="changed($event)` should be called once for each value change

**Steps to reproduce:**

below code will log the `select value has changed` twice each time new select option has been selected

**Related code:**

```html
<ion-header>
    <ion-navbar>
        <ion-title>
            simple select
        </ion-title>
    </ion-navbar>
</ion-header>

<ion-content padding>
    <form [formGroup]="medicationScheduleForm">
        <ion-item>
            <ion-label floating>Select</ion-label>
            <ion-select [interface]="'popover'" (ionChange)="console.log('select value has changed', $event)" formControlName="name">
                <ion-option value="foo">foo</ion-option>
                <ion-option value="bar">bar</ion-option>
            </ion-select>
        </ion-item>
    </form>

    <button ion-button full color="primary" (click)="save()">Save</button>
</ion-content>
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Your system information:

Cordova CLI:  You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.5.0

Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.2.0
Xcode version: Not installed
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us! We will look into this.

**Comment by manucorporat** [comment]
Fixed by @ciekawy!

**Comment by wo-github** [comment]
The problem still exist.

cli packages:
    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2
global packages:
    Cordova CLI : 7.0.1
local packages:
    @ionic/app-scripts : 1.3.7
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.5.3
System:
    Android SDK Tools : 26.1.1
    Node              : v6.9.1
    npm               : 3.10.8
    OS                : Windows 10

```
<ion-select class="headSelect" [(ngModel)]="folder" interface="popover" (ionChange)="changeFolder($event)">
    <ion-option *ngFor="let f of folders" value="{{ f.value }}">{{ f.name }}</ion-option>
</ion-select>
```
The function changeFolder() is called twice.

**Comment by hari-007** [comment]
Still firing twice!!

> 
> Ionic Framework: 3.9.2
> Ionic App Scripts: 3.1.7
> Angular Core: 5.0.3
> Angular Compiler CLI: 5.0.3
> Node: 6.12.3
> OS Platform: Linux 4.10
> Navigator Platform: Linux x86_64
> User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/63.0.3239.84 Chrome/63.0.3239.84 Safari/537.36 



![screenshot from 2018-01-09 15-35-09](https://user-images.githubusercontent.com/5758223/34742751-4106ad36-f555-11e7-839f-de6aee47bda7.png)
![screenshot from 2018-01-09 15-34-42](https://user-images.githubusercontent.com/5758223/34742752-4113e8de-f555-11e7-8c1c-398b052edd64.png)

**Comment by AVManjusha** [comment]
can anybody please help in solving the above-mentioned issue

Current behavior:
for <ion-select (ionChange)="changed($event)"> the changed method is being called twice for each change

Expected behavior:

the (ionChange)="changed($event) should be called once for each value change
