### ISSUE TITLE
[4.0.0-beta.7]  navigateForward to old previous page make ion-back-button missing

### ISSUE THREAD

**Issue by tyroroto** [driftyco/ionic#15436]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.1.1 (C:\Users\kawin\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.0.0
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.0, (and 5 other
plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\kawin\AppData\Local\Android\Sdk)
   NodeJS            : v8.10.0 (C:\Program Files\nodejs\node.exe)
   npm               : 2.15.12
   OS                : Windows 10


```

**Describe the Bug**
Back button (ion-back-button in ion-toolbar)  is missing when navigateForward to first previous page that was navigateBack before current page .

home page -> forward -> page one ( back button ok)
page one -> ion-back-button -> home page
home page -> forward -> page two ( back button ok)
page two -> ion-back-button -> home page
home page -> forward -> page one ( back button missing !)

```
<ion-header>
  <ion-toolbar color="primary">
    <ion-buttons slot="start">
      <ion-back-button></ion-back-button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>
```

**Steps to Reproduce**
1. Click button to navigateForward  to Page 1 (ion-back-button is appear)
2. Click button to navigateBack to home(ion-back-button)
3. Click button to navigateForward   to Page 2 (ion-back-button is appear)
4. Click button to navigateBack to home(ion-back-button)
4. Click button to navigateForward  to Page 1 (ion-back-button is disappear)

**Related Code**
```
In home .page.ts 
    this.navCtrl.navigateForward(page);
In `page` .page.ts 
    this.navCtrl.navigateBack("home");
```

**Expected Behavior**
ion-back-button should still appear for navigate back to previous page  .

**Comment by tyroroto** [comment]
update Steps to Reproduce

**Comment by A-Industry** [comment]
I noticed disappearing back-buttons as well when navigating back and forth between pages. (Beta 3)

**Comment by paulstelzer** [comment]
Keep in mind the breaking change: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#back-button

> The back button is no longer added by default to a navigation bar. It should be explicitly written in a toolbar

So you have to add the back button into your *.html

**Comment by A-Industry** [comment]
Thanks for the link, but I did that. And the explicit html is also there in the bug report. The problem is, is that it is sometimes there, but not always when it should be.

**Comment by tyroroto** [comment]
@paulstelzer 
```
<ion-header>
  <ion-toolbar color="primary">
    <ion-buttons slot="start">
      <ion-back-button></ion-back-button>
    </ion-buttons>
    <ion-title>ชีพจร ความดัน</ion-title>
  </ion-toolbar>
</ion-header>
```
already added

**Comment by paulstelzer** [comment]
Keep in mind that you have to navigateForward to the page so that the button will be shown. If you always want to see a button, add a defaultref:

```
<!-- Back button with a default href -->
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-back-button defaultHref="home"></ion-back-button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>
```

Doc: https://beta.ionicframework.com/docs/api/back-button

**Comment by A-Industry** [comment]
I use the default Angular router. I thought that NavController was something obsolete. Should I still go for that?

**Comment by paulstelzer** [comment]
@A-Industry If you want to have Animations you have to use NavController otherwise you can leave at the Angular Router

**Comment by TrayserCassa** [comment]
If you want to reproduce the issue:

1. Create a Tab Layout with 2 outlets
2. In one of the Tab I have these Items in an ion-content

```
<ion-item lines="full">
    <ion-button href="arbeitsscheine/detail/{{Arbeitsschein.Id}}/auftrag/ist-zustand" routerDirection="forward">
      <ion-icon name="time"></ion-icon>
    </ion-button>
  </ion-item>

 <ion-fab vertical="bottom" horizontal="end">
    <ion-fab-button href="arbeitsscheine/detail/{{Arbeitsschein.Id}}/auftrag/ist-zustand"
                    routerDirection="forward">
      <ion-icon name="md-time"></ion-icon>
    </ion-fab-button>
  </ion-fab>
```

On the ion-item the navigation for ist-zustand-page works. On the floating action button it will use the default href. 
Ist-zustand-page header:

```
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-back-button defaultHref="home"></ion-back-button>
    </ion-buttons>
    <ion-title>Ist-Zustand dokumentieren</ion-title>
  </ion-toolbar>
</ion-header>
```

when you need more info, please tell me.

**Comment by paulstelzer** [comment]
This issue should fixed in beta.12

**Comment by EricKit** [comment]
I still have a bug with this in beta.16 I think. routerDirection="forward" does not produce a back button unless I switch tabs and come back. With defaultHref it always goes to the default URL unless I had already switched tabs. 

Refreshing an app on my home page and clicking a button with routerDirection forward does not produce a back button. Refreshing an app on my home page, clicking any link and going back, then clicking the button with routerDirection does produce a button. For example, I can click the button, no back arrow. Click my browser back arrow, then reclick on the same button, there is a back arrow.
