### ISSUE TITLE
collection-repeat: Order is not preserved

### ISSUE THREAD

**Issue by michelalbers** [driftyco/ionic#1806]
Hi,

if you use collection-repeat with several items the order of the items is **not** preserved. You can specify a ``track by`` function on your own but that doesn't change anything. 

best,
Michel

**Comment by pulakb** [comment]
+1

**Comment by benjoz** [comment]
+1

**Comment by unr** [comment]
:+1:

**Comment by tslater** [comment]
+1!!!!!!!!!!!

**Comment by unr** [comment]
Currently, I've been using [Infinite Scroll](http://ionicframework.com/docs/api/directive/ionInfiniteScroll/) instead.

**Comment by ajoslin** [comment]
Working on this now.

**Comment by ajoslin** [comment]
Can you guys try this in the nightly build? This should be fixed.

**Comment by timmyg** [comment]
@ajoslin if you try @mhartington's codepen from above (http://codepen.io/mhartington/pen/dzLEo) it still doesnt seem to be working, and that one appears to be using the nightly.

It seems to hide it now, but it also isn't there when you scroll back up (try swiping over one of the top ones, scrolling out of the screen, then scrolling back up)

**Comment by ajoslin** [comment]
So this issue is for items losing their order while scrolling.  The item swiping is a separate bug.


See https://github.com/driftyco/ionic/issues/1842#issuecomment-73339019

**Comment by tslater** [comment]
I don't know if this is the exact same, but my observation is that if I add
items to the list (eg. infinte scroll), that the order gets crazy weird.
ᐧ

**Comment by kparks29** [comment]
I am using the latest release v1.0.0-rc.1 and I still seem to have this same issue.
Can we reopen this issue?

When I am scrolling down and then back up the order gets jumbled.

**Comment by mhartington** [comment]
@kparks29 are you seeing this in just a normal collection-repeat demo? Or are you including things like option buttons and infinite scroll?  Could you post a codepen of this?

**Comment by kparks29** [comment]
i noticed it in my own custom one, I actually had 1 way data binding on the child elements and found out that was the issue.  Didn't know 1 way data binding would cause an issue on the children, I knew I couldnt have it on the collection repeat itself.

Also are there any updates on the image performance lag for the collection repeat?

**Comment by mhartington** [comment]
One-way data binding is not advised.
We can't update the data of the elements if all the watchers are disconnected. 

http://ionicframework.com/docs/api/directive/collectionRepeat/

**Comment by ace-han** [comment]
@tslater the same situation +1.
@mhartington already NOT using one-way binding. And still got weird order to display and using v1.1.1

**Comment by RobiFerentz** [comment]
This issue is really annoying. Any ideas for an actual fix?

**Comment by Screeze** [comment]
Also facing this issue, especially when adding items (e.g. using ion-infinite-scroll)

**Comment by kinkay716** [comment]
Also facing this issue while using in conjunction with infinite-scroll. help?

**Comment by christopherfowers** [comment]
Is there an update on this issue?

**Comment by ctesene** [comment]
I see the issue in iOS, but not in the browser. Any updates?

**Comment by leonardobazico** [comment]
+1

**Comment by johannds** [comment]
Also seeing this problem in conjunction with infinite scroll. The scroll position jumps up and then back down sometimes when appending to the Array.
