### ISSUE TITLE
bug: HTML5 video player style messed

### ISSUE THREAD

**Issue by rbarriuso** [driftyco/ionic#1821]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.1</span>  <span ionic-webview>browser</span>

<span ionic-description>The HTML5 video player in Android 4.1 (at least) has a messed appearance due to "ionic.css".

To reproduce the issue create a basic project (using "ionic start" for example) and add the following code to a template:

	<video id="video1" width="480" preload="metadata" controls webkit-playsinline>
		<source type="video/mp4" src="http://www.w3schools.com/html/mov_bbb.mp4"></source>
		<source type="video/ogg" src="http://www.w3schools.com/html/mov_bbb.ogg"></source>
		Your browser does not support HTML5 video.
	</video>

The video player has the appearance in the first attached image. Nevertheless, when removing the line `<link href="lib/ionic/css/ionic.css" rel="stylesheet">` from "index.html", the player has a better appearance, as shown in the second attached image.
![with_ioniccss](https://cloud.githubusercontent.com/assets/7094689/3659700/1be58d06-11b0-11e4-8300-590e6e059c3c.jpg)
![witouth_ioniccss](https://cloud.githubusercontent.com/assets/7094689/3659702/208510c0-11b0-11e4-9ea5-3bd45b680161.jpg)

Original forum post: http://forum.ionicframework.com/t/html5-video-tag-style-messed-in-ionic-css/3254</span>

<span is-issue-template></span>

**Comment by JwJason** [comment]
Six months later and still no fix? This is discouraging.

**Comment by mhartington** [comment]
Should be fixed via https://github.com/driftyco/ionic/commit/7e762b9cbfc4cdd7c2c2997ff44d36abbb66ab8a

Can you all grab a copy of the nightly builds and test it out?

**Comment by Ionitron** [comment]
This issue was fixed via https://github.com/driftyco/ionic/commit/7e762b9cbfc4cdd7c2c2997ff44d36abbb66ab8a

If that is not the case, please leave a comment.

**Comment by uwascan** [comment]
The problem still persists. the controls renders correctly but clicking on the controls does noting. It works in the browser, but fails to play on the device (android 4.4).
