### ISSUE TITLE
bug: Opening Modal randomly causes App to freez

### ISSUE THREAD

**Issue by romanrast** [driftyco/ionic#1912]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>It's hard to reproduce the bug since it happens randomly. But it seems to come with ionic beta10.</span>

<span is-issue-template></span>

**Comment by perrygovier** [comment]
I'm going to call this closed. Let me know if it pops up again.

**Comment by pencilcheck** [comment]
Seems like this is still happening in "driftyco/ionic-bower#v1.0.0-beta.14". Don't know how to reproduce but have receive reports about it.

**Comment by iver56** [comment]
I also experience a freeze for about 4-10 seconds (depends on device) when I click a button that opens a modal. The content of the modal is simple. It has two form inputs and two buttons.

I did a CPU profile in Chrome. What could be the problem?
![image](https://cloud.githubusercontent.com/assets/1470603/5784371/dbcaef74-9dcb-11e4-89d9-a488654c3963.png)

**Comment by perrygovier** [comment]
I've no idea why, but it appears some collection repeat related methods are stuck in a loop. Does the issue still exist when you switch your `collection-repeat` for `ng-repeat`

**Comment by iver56** [comment]
I can now confirm that it is a problem with collection-repeat.

I implemented collection-repeat in the "home" view in my app yesterday. When I go back to a commit before I implemented it, I don't have the "freeze when I try to open the modal" issue.

My scenario is something like this:
From home I can navigate to a "form" view where I can open a modal by clicking a button. It looks like the collection-repeat in "home" is causing problems in the "form" view. Is this because the "home" view is cached and somehow still working and doing lots of stuff in the background?

**Comment by perrygovier** [comment]
@pencilcheck are the instances you're seeing using `collection-repeat` as well?

**Comment by iver56** [comment]
I'm also experiencing the same freeze issue when interacting with (close, open) a popover. Given that I use collection-repeat in that other view I navigated from.

**Comment by pencilcheck** [comment]
@perrygovier actually it's not `collection-repeat`, it's a lot of form and inputs

**Comment by felquis** [comment]
I'm running into this after updating to `v1.0.0-beta.14-nightly-978`

**Comment by stellasoft-will** [comment]
I am also running into this issue, navigate from collection repeat page and modal freezes for around 4 seconds before the app comes back to life. this is a big issue for me as i require to list thousands of items  in collection repeat. any news when this will be fixed.

**Comment by felquis** [comment]
@stellasoft-will this issue was fixed (for me) in the v1.0.0-beta.14-nightly-1011 or newer.

**Comment by stellasoft-will** [comment]
@felquis thanks very much will try that tonight to see if that solves the issue.

**Comment by stellasoft-will** [comment]
I have added the nightly version of v1.0.0-beta.14-nightly-1025 and i am still having issues with collection repeat, not as bad but still unusable. I have tried with just ng-repeat and although for obvious reasons the page load is slow as i am loading 2000+ items the modal is popping up, slowly but still works. any idea for what could help.

**Comment by stellasoft-will** [comment]
@felquis #2964 seems to solve my issue, thanks for your help.

**Comment by ajoslin** [comment]
This is fixed now.

**Comment by dgobaud** [comment]
Still happening lots in 1.7.12 HUGE problem. Might be related to sending app to background, then resuming, then opening modal.

**Comment by rodrigoords** [comment]
I still have this problem, when i dismiss a modal the screen freeze and i need to close app, only happen in device and randomly too.
In my app im using the background app to subscribe one function inside the modal.

**Comment by domisginger** [comment]
@rodrigoords did you find a fix for the issue? I'm having the same, screen freezing on modal dismiss on ionic 3
