### ISSUE TITLE
[ion-side-menus] drag-content="false" only works on first tab.

### ISSUE THREAD

**Issue by kuwabarahiroshi** [driftyco/ionic#2759]
I'm developing an app using `ion-side-menus` which has `ion-tabs` under `ion-side-menu-content`.

I want to disable `drag-content` functionality, so I set the attribute to `false`.

```
<ion-side-menu-content drag-content="false">
```

Yes it works, but only on the first tab if `ion-side-menu-content` has an `ion-tabs` inside it.

Here is a codepen: http://codepen.io/hiroshi-kuwabara/pen/MYeorv

How to reproduce:

1. In a "Home" tab, drag content left or right, and side menu doesn't open (drag-content="false" is working).
2. In "About" tab, or "Contact" tab, drag content left or right, then side menu opens.

**Comment by mhartington** [comment]
Will look at the PR tomorrow

**Comment by halfpt** [comment]
hi @mhartington, please let me know if you would like me to raise a separate issue for this, but wanted to give heads up as you mention you will be looking into this fix. 

I applied the PR fix above, and now the content respects the 'drag-content="false"' attribute, however when arriving from a separate (non-tab) login state, the attribute edge-drag-threshold=.. on 'ion-side-menu-content' is ignored; you can drag from anywhere in the page.

Codepen forked from above below demonstrates:
http://codepen.io/halfpt/pen/LELbXa

**Comment by mhartington** [comment]
@kuwabarahiroshi #2752 was merged, can you confirm your issue was resolved by testing the nightly builds?

@halfpt please open a new issue for this.

**Comment by kuwabarahiroshi** [comment]
@mhartington Thanks a lot!
I confirmed that the issue is resolved with the nightly builds.
I tested it on Chrome(Mac), iPhone, Android.

**Comment by ritvick** [comment]
I still face this issue, I have disabled caching completely so that my controllers are executed everytime. 
In my controller I have $ionicSideMenuDelegate.canDragContent(false);

It does work for the first time, but after switching few states and returning back to the state which invokes that particular controller, but  $ionicSideMenuDelegate.canDragContent(false); doesn't stop it anymore.

**Comment by beekermememe** [comment]
@ritvick : Have you tried  - $scope.$on('$ionicView.afterEnter', function(){}), I have used this in the past?

**Comment by ritvick** [comment]
Yes thats what I was thinking, I have  $ionicSideMenuDelegate.canDragContent(false); defined in my controller, but I think this is executed after the view is loaded and then it does not have any effect on that view. Though if I move to other view then it works as expected.

1. Where I shall define $scope.$on('$ionicView.afterEnter', function(){}) ?
Inside run function ? 
2. Do I need to specify $ionicSideMenuDelegate.canDragContent(false); inside above mentioned inline function ?

**Comment by mhartington** [comment]
Can you all please provide a codepen or demo and test it against the nightly builds?

**Comment by fhofer** [comment]
I know it's not exactly the same problem but some kind of similar one:
I'm on an app based on the principle of another app which goes around here and does not show the tab bar before "Sign in" is clicked.
Now the combination of this app and the side menu starter app brings back this problem: As long as you are not on the tab page everything is fine but as soon as you open the view with the tab bar, it's possible again to swipe in the side menu (found out because it interferes with your image slider).

Thanks for any feedback!

**Comment by plnkr2015** [comment]
hi,

while   <ion-side-menu-content drag-content="true"> works great.
but if i use it on the tab where map is there then map event listeners (like drag, dragstart, dragend etc) are not working. 

i would like to design in such a way that on that tab when user drags the map i can listen to the map even listeners and at the same time disable the ionic side menu drag content.

how to achieve that?

please help.
regards,
