### ISSUE TITLE
bug: $ionicSideMenuDelegate.canDragContent(false) no longer works

### ISSUE THREAD

**Issue by keithdmoore** [driftyco/ionic#2957]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>With beta14, this no longer works:

$ionicSideMenuDelegate.canDragContent(false);

I have only tried this on the desktop,  it might affect all platforms.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings, @keithdmoore!

We are now requiring all issues to be submitted through our custom issue form so that we have all of the information necessary to fix them as quickly as possible.

Your progress on this issue has been saved at the following url:

[link to Ionic issue form](http://ionicframework.com/submit-issue/#/?iid=2957)

This issue will be closed if not resubmitted through the form. Please fill out the rest of the form so that we may assist you.

Thank you for allowing me to assist you.

**Comment by gnoumaster** [comment]
I confirm, I have this bug in all android versions.

**Comment by keithdmoore** [comment]
I have a side menu app with tabs.  On one of the tabs I have tinder cards and I would like to prevent the side menu from being displayed upon dragging the content.

@gnoumaster what scenario are you seeing an issue?

**Comment by keithdmoore** [comment]
@mlynch Can you help out with this?  It appears to only be a problem when you invoke a url from an ion-tab

**Comment by keithdmoore** [comment]
@gnoumaster This codepen may help you if you have a straightforward usecase.

http://codepen.io/keithdmoore/pen/JoNGgB

**Comment by gnoumaster** [comment]
I have the exact same usecase than you, so It won't help you a lot :)

I also noticed that the side menu drag don't work anymore when I call on my side-menu/ion-item a function (with ng-click & $state.go) instead of a direct url (href)

**Comment by mhartington** [comment]
So I took a look at everything, saw the issue you were describing, tried to replicate it in a codepen,

http://codepen.io/mhartington/pen/wBdORX

But wasn't able to replicate the issue @keithdmoore

**Comment by keithdmoore** [comment]
@mhartington I appreciate your efforts.  I too am unable to reproduce in a codepen.  However, I can reproduce it in an app.  Another odd thing is that if I refresh the url for the view that I want the drag content to be disabled,  it works.  However, as soon as I restart the server, back to not working.  It might be related to ionic serve?   Here is the project: https://github.com/trendicity/trendicity/tree/beta14

I would be grateful if you could have a look at that project.

**Comment by mhartington** [comment]
I will continue this over here
https://github.com/trendicity/trendicity/issues/37

**Comment by keithdmoore** [comment]
My issue ended up being an issue where the default route was a view that integrates with Google maps.  For some reason this was causing this issue.  When I changed the default route to a different view, everything works as designed.

**Comment by keithdmoore** [comment]
@gnoumaster If you are still having an issue, feel free to reopen.

**Comment by keithdmoore** [comment]
Still having an issue.
View 1 - dragContent should be disabled.
View 2 - dragContent should open the side menu.

If the default route goes to View 2 and then I navigate to View 1, I am still able to open the side menu by dragging the content.

However, if the default route goes to View 1, I am not able to open the side menu by dragging the content.  Navigating back and forth between View 1 and View 2 works fine.

**Comment by mhartington** [comment]
Are you wrapping the `canDragContent()` in view events?

**Comment by keithdmoore** [comment]
You mean like this:

```html
  // Disable side-menu drag so that it doesnt interfere with our tinder cards functionality
  $scope.$on('$ionicView.enter', function() {
    $timeout(function(){
      $ionicSideMenuDelegate.canDragContent(false);
    });
  });
```

Yes

**Comment by keithdmoore** [comment]
Workaround was to do this:
````javascript
  $scope.$on('$ionicView.enter', function() {
    $ionicHistory.clearHistory();
    $ionicSideMenuDelegate.canDragContent(false);
  });
````

@perrygovier and @mhartington will work on a more permanent solution.

**Comment by mica16** [comment]
+1 for your workaround @keithdmoore

**Comment by adamdbradley** [comment]
When using the lifecycle events I've been able to get this to work with:

```
$scope.$on('$ionicView.enter', function () {
    $ionicSideMenuDelegate.canDragContent(false);
});
```
Why was the `clearHistory()` necessary?

**Comment by keithdmoore** [comment]
No permanent fix?

**Comment by keithdmoore** [comment]
@perrygovier can fill you in

**Comment by keithdmoore** [comment]
I just took @mhartington codepen above and added enable-menu-with-back-views="false" to the 
ion-side-menus tag and verified that this is fixed in nightly without the clearHistory() call.  I also was able to reproduce the problem with beta14 in the codepen.  Looks like this got fixed.  Thanks guys!

**Comment by circuitrider** [comment]
On v1.2.1 this is still broken.

**Comment by riskmanagerjeff** [comment]
I think this is still broken on 1.2.4.
I noticed that on first loading, it works fine.  However, when navigating to a tab via a href link in the sidebar, the problem shows up.

**Comment by coderReview** [comment]
Could re-open this? I can't use with the clearHistory fix. Since I need to disable menu swipe in a detail page in a master-detail app. If I clear the history I can't go back to previous page anymore. Thank you.

**Comment by riskmanagerjeff** [comment]
i did a workaround that might work for you.  basically, I disable the the .candragcontent on $scope.$on( view.enter ) on each controller every time.  this seems to achieve the desired affect for me.  Hope that helps.

**Comment by coderReview** [comment]
@riskmanagerjeff will try that. Thanks

**Comment by sefsinalas** [comment]
@keithdmoore do you remember how to solve the issue when it involves google maps? Im having the exact same problem

**Comment by keithdmoore** [comment]
@sefsinalas Same as above.  See https://github.com/trendicity/trendicity/blob/master/www/js/controllers/map.js as well for what to do when leaving the map view.

**Comment by muhdmurtaza** [comment]
I am using 1.7.14. In my case, I set $ionicSideMenuDelegate.canDragContent to true or false in the controller for each state (I do not want the user to navigation away in certain places). 

Sadly, $ionicSideMenuDelegate.canDragContent(true); simply does not seem to work. When I navigation around and return, it suddenly works. This is very frustrating. The only solution that works every time is when I use $ionicHistory.clearHistory(); before setting the canDragContent to true or false.

Of course, if you need the history, this will be a problem. However, for time being, I am just going with this workaround. Hopefully someone posts here when Ionic team fixes this bug so I can remove the clearHistroy().

**Comment by aj-thilakan** [comment]
Can we reopen this to get a proper fix, we cant use the workarounds.

**Comment by smancebo** [comment]
i have the same problem, $ionicSideMenuDelegate.canDragContent(true) works if you clean the History, but if you need the history, there is another way?
