### ISSUE TITLE
bug: Ion Content inside Slidebox can scroll and swipe at the same time

### ISSUE THREAD

**Issue by ghost** [driftyco/ionic#3239]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I'm not sure if it is intended, but the issue isn't in earlier versions, and the changelogs don't seem to mention it.

When using an ion-slide-box where each slide contains an ion-content (or an ion-scroll), you are able to scroll the content vertically, while swiping the slides horizontally. In previous versions of Ionic, this behavior was locked to moving one at a time.

Here's a codepen that reproduces the issue. Try grabbing the slide and moving horizontally, then vertically, you can scroll the inner content while swiping the slides. However, if you scroll the content vertically, and then attempt to swipe left/right, you are locked.

http://codepen.io/squeaky-clean/pen/JorvzR</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @squeaky-clean!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3239). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3239)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by zlpghost** [comment]
yes, definitely a bug, should be fixed ASAP

**Comment by vlad-bezden** [comment]
This issue still exists in v1 rc2 build. Do you know when this is going to be fixed?

**Comment by quanghoc** [comment]
+1

**Comment by Ionitron** [comment]
Greetings @ghost!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
