### ISSUE TITLE
bug: Slidebox Gets Messed Up After Opening a Popover 

### ISSUE THREAD

**Issue by shaulhadar** [driftyco/ionic#3245]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>4.4</span>  <span ionic-webview>webview</span>

<span ionic-description>Hello Ionic Team.  I have found a bug.  if you have a slidebox, and than go to a page that has a popover, and you open the popover, and than go back to the page with the slidebox, you will see that the slidebox gets messed up.  strangely, if i change the orientation of the phone to landscape and than back to portrait it fixed it, but this is definitely a bug. 

Please fix this for next update, and in any case you can't see it let me know and i will upload you a folder with the problem.
Thanks for your time,
Shaul.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @shaulhadar!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3245). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3245)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by Elvistelefon** [comment]
You could update the slidebox when entering the view again like this:
```
$scope.$on('$ionicView.beforeEnter', function() {
    $ionicSlideBoxDelegate.$getByHandle('you-swipe-handle').update();
});
```

Don't forget to add the delegate handle

    <ion-slide-box delegate-handle="'you-swipe-handle">

**Comment by shaulhadar** [comment]
Hi and thanks. I will check it out ;)

**Comment by tolu360** [comment]
This issue had persisted since beta 14 or so, for some reason opening a popover in a different view resets the width of the ```div.slider-slides``` to 0 such that returning to the view with the slidebox is distorted. 

I resorted to doing something similar to what @Elvistelefon suggested above:

```
$scope.$on('$ionicView.beforeEnter', function() {
    ionic.trigger('resize', {target:window});
  })
```

But I think it maybe something for the Ionic Team to look at.

**Comment by weases** [comment]
I am facing the exact same problem using rc-1. Just wanted to emphasize that this is not related to any specific platform. It can be reproduced on desktop chrome as well.
Resizing the window fixes it, though.

**Comment by shaulhadar** [comment]
Yeah, I did some more tests and it is quite a nasty bug.   It actually consists of two parts, the first part is that the width or height gets messed up, and the second problem is that the slider doesn't start from the begining when opening the page, after you saw the slider....

I checked a number of frameworks that have sliders, and this doesn't happen in none of them... so I assume that this is a bug that the ionic team is aware of and that they are going to push a fix in one of the next rc version :) at least, I really hope so ...

**Comment by RangerRick** [comment]
Yup, I'm seeing the same issue: http://i.imgur.com/6kMzCy2.png

I have 2 canvases inside 2 slide boxes, when I navigate to a popup and back to my main dashboard view, the canvases are on top of each other.

I can confirm that @tolu360's workaround works for me:

```javascript
$scope.$on('$ionicView.beforeEnter', function() {
    ionic.trigger('resize', {target:window});
  })
```

**Comment by edparsons** [comment]
Hey, guys so I had this issue and it seems to be opening the popup triggers the resize on sliderbox even if it's in a cached view. I've written a pull request for the ionic team to fix the issue and I'm waiting for it to be accepted. If there's any way to up vote the pull request that would be cool.

**Comment by mhartington** [comment]
I believe this was fixed in RC3. Can you please confirm this?

**Comment by weases** [comment]
Hey Mike,
I am afraid I am still facing this issue.
Please, see this [Codepen](http://codepen.io/weases/full/JdPjWx).

**Comment by edparsons** [comment]
This is fixed in master, I don't know which version it was pushed into though. The fix is on line 46 of this file https://github.com/driftyco/ionic/blob/master/js/views/sliderView.js

But those lines definitely aren't there on codepen.

**Comment by mhartington** [comment]
@weases I may have been mistaken about the version number, it is fixed in the nightly builds.

http://codepen.io/mhartington/pen/RPbRPX

**Comment by tolu360** [comment]
I'm glad to know that. Thank you Ionic team!

**Comment by weases** [comment]
aaah, I see. Thanks for the clarification, Mike.
