### ISSUE TITLE
bug: ion-spinner has memory leak

### ISSUE THREAD

**Issue by realityfilter** [driftyco/ionic#3583]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>

# Problem 1:

The current implementation does not cleanup on the deletion of the scope. This leads to a memory leak. The spinning animation keeps on running even if the spinner is not in the dom anymore. The animation should be stopped when the scope gets destroyed. This degrades scrolling performance too.

# Problem 2:

The spinner in combination with the infinite-scroll directive.

```
ion-infinite-scroll {
  ...
   
  .icon:before,
  .spinner{
    -webkit-transform: translate3d(0,0,0);
    transform: translate3d(0,0,0);
  }
  &:not(.active){
    .spinner,
    .icon:before{
      -webkit-transform: translate3d(-1000px,0,0);
      transform: translate3d(-1000px,0,0);
    }
  }
}
```

It is not sufficient to have the spinner translated out of view. (Why this solution was chosen instead of opacity?). The spinner is still getting animated and degrades scrolling performance on iOS devices a lot. Even if out of view.
</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @realityfilter!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3583). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3583)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mhartington** [comment]
Any way you could provide a demo of this?

**Comment by berndartmueller** [comment]
I can reproduce this bug with a blank ionic template and a simple ionicLoading statement -> http://forum.ionicframework.com/t/rc0-1-high-idle-cpu-usage-on-ios-7-iphone-4/19705

**Comment by krik** [comment]
If you don't rely on the spinner, here's a quick workaround for the memory leak: 

	$provide.decorator('ionInfiniteScrollDirective', function($delegate) {
		var directive = $delegate[0];
		directive.template = null;
		return $delegate;
	});

**Comment by perrygovier** [comment]
Ok, I've noticed a few issues around this and have tried to consolidate them. This looks like a big deal. Thanks everyone for chiming in and submitting issues about this.

**Comment by mica16** [comment]
Hi,

Any news about this major issue ?
Several users have uninstalled my app because of the CPU keeping running at 30% .. while the app is in background. 

Thanks

**Comment by perrygovier** [comment]
Digging in to this a bit more, setting `display:none` on the inactive spinner instead of moving it off screen significantly improves memory usage. Here's the instruments readout of the infinite scroll test when it starts with just two elements and infinite scrolls in a loop until it reaches the height of the initial page. The first is the current approach followed by `display:none`.

![screen shot 2015-06-11 at 12 32 38 pm](https://cloud.githubusercontent.com/assets/571056/8113921/e9c03f7a-1036-11e5-8be3-2c80ab00ea6c.png)

![screen shot 2015-06-11 at 12 33 41 pm](https://cloud.githubusercontent.com/assets/571056/8113929/f20f4bbc-1036-11e5-8e8f-49f2bc448b66.png)

This will potentially cause a flicker on some devices. I'm going to re-evaluate across a rance of devices bearing this significant memory impact in mind. 

Stay tuned.

**Comment by mica16** [comment]
Interesting, I stay tuned :)

**Comment by perrygovier** [comment]
fixed in 32da5cdc9d4ef53904a656f82ae574d085500cc7
I'm going to take a look at loading too. Note, set the spinner to `display:none` when not in use. Spinners are cool, but they eat a lot of memory.

**Comment by mica16** [comment]
Will it be integrated in nightly build soon? 

Thanks for the fix

**Comment by mica16** [comment]
I've just tested your fix. 
But it doesn't solve the issue. 
I have this block upon my list:  
```<ion-refresher style="color: rgb(30,30,30)"
                   pulling-text="Pull to refresh..."
                   pulling-icon="ion-arrow-down-c"
                   on-refresh="doRefresh()">
  </ion-refresher>```
Still 30% of CPU when app remains in background. 

When removing this block (removing the pull-to-refresh feature) => CPU 0% as expected.

Any idea?

**Comment by mica16** [comment]
@perrygovier The code you fixed concerns infinite scrolling in ```_scaffolding.scss```. It lacks the fix for pull-to-refresh. Am I right?

**Comment by mica16** [comment]
Tested it and it works great, thanks ;)

**Comment by promactkaran** [comment]
So, I tried this, And I have one question. Un-till I scroll down the list and reach the bottom. There are Layer Paints, which are always increasing even though the I am no where near to the end of my List. 
![screen shot 2015-06-26 at 4 56 54 pm](https://cloud.githubusercontent.com/assets/10154253/8376409/8c72e10c-1c24-11e5-9e0c-8cffe4108880.png)

the ion-spinner.spinner.spinner-ios	Element - is always increasing the Layer Paints


![screen shot 2015-06-26 at 4 57 10 pm](https://cloud.githubusercontent.com/assets/10154253/8376418/b72b47b8-1c24-11e5-83e1-308651f3af9d.png)

Is this a bug? or Its a normal behaviour ? 

Platform : iOS
Ionic: 1.0.0v (scss/_scaffolding.scss fix applied)

**Comment by mlynch** [comment]
Should be fixed by: 9f341a8ccb3829ccb5a02797bd44ec301f6bb14f

**Comment by gbrussa** [comment]
Issue appears to be still present on v1.2.4, the spinner causes infinite amount of layers keeping CPU busy and draining battery, even if it's never shown.
Setting my refresher to spinner=none solves the problem.
![image](https://cloud.githubusercontent.com/assets/9541438/12996452/a9dc3708-d10e-11e5-972c-db4790a2f7f5.png)

**Comment by vascofernandes** [comment]
Still present in 1.2.4.
CPU. constantly at 40/50%

        <ion-refresher pulling-text="Refresh" on-refresh="vm.doRefresh()">
        </ion-refresher>
