### ISSUE TITLE
bug: cached views don't update their $stateParams when being reused

### ISSUE THREAD

**Issue by rob3c** [driftyco/ionic#3884]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hi everybody,
,
First of all, I love the cached views feature, so thanks for adding those!

Unfortunately, it looks like there's a bug when hydrating them from the cache, though, in regards to their $stateParams. They seem to retain their initial values when the views are first instantiated, regardless of what is sent later, at least in certain circumstances. It just doesn't seem like that's the intended behavior.

I created this codepen to walk through reproducing the bug:
http://codepen.io/rob3c/pen/ZGLNNp

As the demo shows, the idea is to spread editing of a single document across tabs in a single transaction, with each tab being a named state that is directly linkable from elsewhere in the app. Of course I can set cache: false in the views, but I like how cached views remember their state (scroll position & such) while switching between the tabs.

The codepen app has popups in the $stateChangeStart and $ionicView.enter events that show what the toParams are when navigating between the tabs, as well as the problems that arise when trying to update the view when they don't contain the correct values.

Thanks in advance for taking a look!
Cheers,
Robert</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @rob3c!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=3884). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=3884)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by dreamershl** [comment]
+1 I encounter this issue too now ;(

**Comment by dreamershl** [comment]
I believe this issue is caused by the closure. the way which we use to access the $stateParams is through the injection in the controller constructing stage. while the event, "$ionicView.enter", is just reuse that injected variable "$stateParams". If switch to the "$state", you can get the latest state parameter in its attribute "$state.params".

The key is the $state is a provider. it will always get the current transition parameter

        $state.params = toParams;
        copy($state.params, $stateParams);

**Comment by rob3c** [comment]
Yes, the issue is caused by the closure on $stateParams when the controller is constructed. Unfortunately, using the $state provider doesn't help, because it never has a useful value to work around the problem within the two events of interest: `$stateChangeStart` or `$ionicView.enter`.

Inside the `$stateChangeStart` event, the `$state.params` object still has the current state value - i.e. it's equal to `fromState`, *not* `toState` - because the state transition hasn't happened yet.

And in the `$ionicView.enter` event, the `$state.params` object has already been set to the incorrect value saved in the original `$stateParams` closure, so there's no way to get the correct `toParams` at that point without managing it yourself externally via a hack using your own state management.

**Comment by rob3c** [comment]
Oh, and `$state.params` is read-only, so you can't change it in the `$stateChangeStart` event, for example, even if you could get the correct value there.

**Comment by Freundschaft** [comment]
so for the time being the solution is to disable cache for affected states?

**Comment by kashban** [comment]
Facing this issue too. This is quite an upset and very hindering using cached views.

**Comment by ta4ka** [comment]
I faced the same issue on my sub views. I fixed it by adding:
cache: false in my state
      .state('chat', {
                url: "/chat",
                templateUrl: 'templates/partials/Chat.html',
                controller: 'ChatCtrl',
                cache: false,
                params: {
                    userId: null,
                    friend: null
                }
            })

**Comment by kashban** [comment]
@ta4ka Yeah, that's a possible workaround, but not always recommendable on pages with complex GUIs and Controller initialization. 

I took another approach and stored any paramter for the View within a factory, which survives between view changes. Probably not very elegant but you don't lose the ability to cache views. 

To read the parameter stored in the factory I register an event handler :

    	$scope.$on('$ionicView.beforeEnter', function() {
    		// $stateParams not working here if the view has been cached, so resort to service
    		$scope.model.assetqrcode = workordersService.getCurrentAssetQrCode();
        });

**Comment by Freundschaft** [comment]
is that really the solution? That's not a very nice fix. :(

**Comment by kashban** [comment]
@Freundschaft No, that is not nice but a valid workaround until the bug is fixed by Angular/ionic. Another one could be using URL parameters.

**Comment by Freundschaft** [comment]
It also seems that the resolve function is not called on cached views, which breaks a lot of things as well :(

**Comment by vamsivarikuti** [comment]
The values injected from `ui-router` resolve function are cached, I can see the new values in the resolve function but inside the controller it still shows old values, I expected the new values from the server injected into the controller.

**Comment by herve1976** [comment]
I am having the same issue. Still no solution for this one?

**Comment by jhluedke** [comment]
I am also having this issue, is there a workaround that lets me keep caching the state?

**Comment by Freundschaft** [comment]
the suggestion by @kashban would be a valid workaround for that I suppose

**Comment by raowl** [comment]
not fixed yet? had the same problem

**Comment by nbering** [comment]
I'm not usually one to +1 an issue, but I just encountered the same issue. The `cache: false` workaround is fine for the moment. Is there any plan to fix it, or could someone point me in the right direction to figure this thing out and fix it for myself? Cached views are great, but passing different params should immediately invalidate the cache.

**Comment by ffabreti** [comment]
I think we should setup a factory to store such "flying" parameters, as said by Ionic member [here](https://github.com/driftyco/ionic/issues/4124).
This way your code would still be functional within Ionic v2.

**Comment by VinceOPS** [comment]
+1, same issue here, as views are in cache, $stateParams is not updated.

**Comment by kanchangxin** [comment]
+1, same issue here, as views are in cache, $stateParams and $state.params is not updated.
A页使用paramest接受参数，跳转到B后 返回A，A接受的paramests值是第一次进入的，以后不再变化？

**Comment by thiagofelix** [comment]
Hi.

Have you guys tried something like this already?
https://gist.github.com/thiagofelix/3c16e9cae0e03eebd351

I've been using this workaround to ensure $stateParams and currentView params are always in sync.

**Comment by Freundschaft** [comment]
nice! is there any downside of using this workaround? And if not, would there be any reason to not include that in ionic itself? :+1:

**Comment by danbucholtz** [comment]
Hello,

This seems to be working by design (designed by ui-router).  It seems like the ui-router suggested path is to A) not cache the view, or B) use a singleton service/factory to pass data around in memory.

Thanks,
Dan

**Comment by danbucholtz** [comment]
I began investigating a fix for this.  Turns out this functionality is already in place.  We just need to document it.  The docs will go live shortly.

Here is the way to access the state params .

```
$scope.$on("$ionicView.beforeEnter", function(event, data){
   console.log("State Params: ", data.stateParams);
});
```

The same concept works for the `$ionicView.enter` and `$ionicView.afterEnter` events.

**Comment by rob3c** [comment]
@danbucholtz Unfortunately, that `data.stateParams` is the same stale cached value, so it doesn't address the problem. You can confirm it using my original codepen repro from the original bug report:

http://codepen.io/rob3c/pen/ZGLNNp

Just log `data.stateParams` to the console in `$ionicView.enter`, for example.
I know the repro is a little bit complicated, but only minimally so to guarantee hitting the bug. It carefully leads through causing it to manifest. You have to be careful how you're reproducing it, because it's easy to get fooled and not really be pulling a cached view in simple scenarios.

Also, even if that did work, what about  $stateChangeStart? What if we want to make navigation decisions based on `toParams`?

**Comment by danbucholtz** [comment]
@rob3c, this code pen should illustrate a cached view accessing the parameters from the life cycle events.  It seems to be working for me.

http://codepen.io/danbucholtz/pen/PNKBNa?editors=1010

Let me give the $stateChangeStart some thought.

Thanks,
Dan

**Comment by pavei** [comment]
+1

**Comment by tgensol** [comment]
+1

**Comment by nbering** [comment]
@danbucholtz I'm sorry. While that works, it's a terribly verbose workaround. Users picking up ionic that are familiar with ui-router should just be able to use stateParams as they always have. Why do we have to add 50 lines of code to a controller to update stateParams?

**Comment by danbucholtz** [comment]
@nbering - Unfortunately this is how it has to be due to view caching.  The alternative is to not cache your views.  Controllers are only created once and dependencies are created/injected once.

```
$scope.$on("$ionicView.enter", function(event, data){
   $scope.selectedItemId = data.stateParams.selectedItemid;
});
```

**Comment by nbering** [comment]
Understood. I've turned off view caching as the work-around in my application. I really have no need to cache my views anyway since the data is fetched via route-resolve on every view transition anyway.

**Comment by rob3c** [comment]
>  Can you help me out with what isn't working correctly for you?
@danbucholtz my initial codepen repro in the first post was carefully crafted to lead you through exactly what isn't working correcly once you reach step 6. Since the devil is in the details, the code explains is better than vague comments here. It pulls from nightly and has been continuously broken since I originally posted it almost a year ago. Unfortunately, your simplified codepen does not surface the problem.

**Comment by danbucholtz** [comment]
Hi @rob3c,

I am not seeing the issue if you are accessing the state params from the life cycle event.  Are you?

Please let me know.

Thanks,
Dan

**Comment by a2ron** [comment]
+1

**Comment by Freundschaft** [comment]
so as far as I understand, for stateparams there is a fix in place, but for the resolve feature of UI router there is still nothing, right?

**Comment by danbucholtz** [comment]
`Resolve` via ui-router is not supported in Ionic.  State params via life cycle events is to facilitate view caching and still have the latest data.

Please see documentation here:
http://ionicframework.com/docs/api/directive/ionNavView/

**Comment by Freundschaft** [comment]
okay thats understood, but this way its not possible to ensure that a promise is resolved before a view is loaded, right?

**Comment by rob3c** [comment]
If by "state params via life cycle events" you're including accessing `data.stateParams` or `$state.params` from within `$ionicView.enter`, then those definitely still do NOT have the latest data in the example that I posted.

**Comment by luckycadow** [comment]
@rob3c Did you ever find a way to deal with this other than disabling cached views?

**Comment by rob3c** [comment]
@luckycadow Nope, and it's unlikely to ever be fixed since this was closed under the assumption that's it's already working fine ;-) Anyway, the only workaround is to completely manage the params yourself outside the ionic mechanism, or just architect your app in a simpler way that doesn't trigger the problem.

**Comment by wmenegali** [comment]
Yeah, same problem here and it still doesn't work!
