### ISSUE TITLE
bug: Ionic view lifecycle event fired inaccurately

### ISSUE THREAD

**Issue by NgYueHong** [driftyco/ionic#4555]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>I am trying to do something with the ionic view lifecycle event such as `$ionicView.afterEnter`. However, I always experience that the event is fired inaccurately. For example `$ionicView.afterEnter` code will be executed even the view is not even ready yet. After long testing I found that the inaccuracy happen when I have `$ionicConfigProvider.views.transition('none');` in my code. Hope to see a fix for it soon.</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @NgYueHong!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4555). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4555)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hey @NgYueHong, I just pushed a fix for a related issue, can you try master for me?

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Since it has been a little while since there was any activity on this issue i will be closing it, but feel free to reopen this issue if needed!

**Comment by NgYueHong** [comment]
@jgw96 Hi, my latest trying still seems to be the event is fired inaccurately. Not really fixed on version 1.2.4.

**Comment by jgw96** [comment]
@NgYueHong would you mind sharing a code sample, plunkr or codepen with us so that we can reproduce your issue?

**Comment by NgYueHong** [comment]
@jgw96 I am experiencing the problem when using ionic-native-transitions (https://github.com/shprink/ionic-native-transitions) or even NativePageTransitions (https://github.com/Telerik-Verified-Plugins/NativePageTransitions) with ionic. You need to test it with low end device such as ZTE V815W and also the heavy page to better see the problem.

As the code is quite complex and involve plugin, so I can't do it with plunkr or codepen. Do you have alternative way to send you the sample?

**Comment by jgw96** [comment]
@NgYueHong could you could set up a repo with the code thats having the issue that way i can clone it and try it myself?

**Comment by jgw96** [comment]
As it has been a little while since there was any activity on this issue I will be closing it for now, please feel free to reply if you are still experiencing this issue though!
