### ISSUE TITLE
Bug: Checkboxes uncheck and recheck themselves inconsistently on iOS

### ISSUE THREAD

**Issue by louisdoe** [driftyco/ionic#4698]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>Hi,

I have three checkboxes in my app, and when I click on them in the iOS simulator, it's as if I had clicked twice: they uncheck and recheck themselves inconsistently.

Everything's fine on Android.

To reproduce this bug, just create Checboxes in a template and test in iOS simulator (iPhone 5 portrait, iOS 8.4).

```
<div id="wavetypes" class="row">
			<div class="col">
				<label class="checkbox checkbox-blueboardline">
					<input type="checkbox" ng-model="dataCheckbox.type1" ng-true-value="1" ng-false-value="''"></input>
					Small Waves
			   </label>
			</div>
			<div class="col">
				<label class="checkbox checkbox-black">
					<input type="checkbox" ng-model="dataCheckbox.type0" ng-true-value="0" ng-false-value="''"></input>
					Normal Waves
			    </label>
			</div>
			<div class="col">
				<label class="checkbox checkbox-greyboardline">
					<input type="checkbox" ng-model="dataCheckbox.type2" ng-true-value="2" ng-false-value="''"></input>
			      	Step-Ups
			      </label>
			</div>
		</div>
```</span>

<span is-issue-template></span>

```
in the corresponding controller: 

```
$scope.dataCheckbox = {};
$scope.dataCheckbox.type1 = '';
$scope.dataCheckbox.type0 = '';
$scope.dataCheckbox.type2 = '';
```

My system information:

Cordova CLI: 5.3.3
Ionic Version: 1.1.1
Ionic CLI Version: 1.7.11
Ionic App Lib Version: 0.6.5
ios-deploy version: 1.8.2 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v4.2.1
Xcode version: Xcode 7.1 Build version 7B91b

**Comment by Ionitron** [comment]
Greetings @louisdoe!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4698). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4698)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by louisdoe** [comment]
Did I put enough info in this issue ? Can someone please advise me on how to write this so you can have a look at it ? I have been stuck with this for several days. Thanks

**Comment by mlynch** [comment]
@louisdoe what version of Ionic are you using? We had a number of checkbox issues fixed recently.

**Comment by louisdoe** [comment]
Hi @mlynch I am using ionic 1.1.0
Do you think it is already fixed in 1.1.1 ?

**Comment by louisdoe** [comment]
I have just tried with ionic 1.1.1, I still see the issue.
Can you please help me on this, it's stalling the progress on my app.
Thanks

**Comment by louisdoe** [comment]
My checkboxes control (filter) a big list below in a collection repeat, it seems that if I remove this list, the issue disappear...
Whoa, it's a bit too complex for me here, can someone help me figure this out ? I could give access to my code if necessary.
Thanks

**Comment by louisdoe** [comment]
Can someone please help me here I am stuck !!

**Comment by louisdoe** [comment]
The click event fires twice, for a single tap !!! Can you please help me ?

**Comment by PerfectionCSGO** [comment]
http://stackoverflow.com/questions/30706214/prevent-ios-autofocus-first-input-when-page-opens-ionic 

This is related. I have the same issue in the iOS Iphone 5S simulator (running iOS 9.2). 

My use case: I open the side menu and click on logout. Right underneath where I would have clicked is my input from the login view. Causing it to auto focus and then all sorts of wierd scrolling behavior happens.

I assume this happens on our actual iPad but then the logout button doesn't appear on the same x,y cords as the input fields.

**Comment by louisdoe** [comment]
@PerfectionCSGO thanks for for backing this, I feel so alone in here ! This bug is really annoying and preventing me from publishing, I can't find a way to even workaround.

Did you find a fix yourself ?

**Comment by patrickmcd** [comment]
I'd recommend switching over to [ion-checkbox](http://ionicframework.com/docs/api/directive/ionCheckbox/), or [ion-toggle](http://ionicframework.com/docs/api/directive/ionToggle/).

They aren't supporting label tags anyway. Check out this [blog post](http://blog.ionic.io/announcing-ionic-1-2/) and look at the **Form Inputs** and **Radio and Checkbox** sections.

**Comment by PerfectionCSGO** [comment]
@louisdoe I just implemented $ionicLoading when logging out as a work around.

**Comment by louisdoe** [comment]
@patrickmcd I switched to the ion-checbox directive as you recommended. And the bug is still here !
Could someone take over my code to see for himself ?

@PerfectionCSGO ok thanks. I don't think I can do this in my checkbox case. But can you give me some code so maybe I get inspired ? ;) thanks.

**Comment by PerfectionCSGO** [comment]
I reuse this code.
```
    function (type) {
        $ionicLoading.show({
            template: '<p>' + type + '</p><ion-spinner icon="android"></ion-spinner>'
         });
    },
```

**Comment by louisdoe** [comment]
@PerfectionCSGO  thanks for your code.

I am not sure how to defer the checkbox click, do you have an idea ?

I tried on codepen but I can't really find a way to reproduce the bug. Plus, it is only on iOS webview, would it be possible to check a codepen as a webview?

**Comment by louisdoe** [comment]
Is there someone in the ionic team who could directly check our code (I'll grant access to our repo) ? This bug seems highly difficult to reproduce. 
Thanks

**Comment by keyban** [comment]
i am getting a related issue with a modal which when clicked on a close button the underneath button is clicked as well. 
concrete issue: everytime when i close my modal with a button (ng-click) on the bottom right corner the tab bar underneath the modal is clicked

Info:
Cordova CLI: 6.0.0
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.2 
ios-sim version: 5.0.2 
OS: Mac OS X El Capitan
Node Version: v4.0.0
Xcode version: Xcode 7.2.1 Build version 7C1002

is there some help around? getting crazy with that issue

**Comment by danbucholtz** [comment]
@louisdoe, @keyban, can you provide a codepen to demonstrate/recreate the issue?

Thanks,
Dan

**Comment by louisdoe** [comment]
I did one when opening [this thread](https://github.com/driftyco/ionic/issues/5127)

http://codepen.io/LouisDoe/pen/gPvGXe?editors=1000

**Comment by danbucholtz** [comment]
Hi @louisdoe, can you give me step-by-step instructions on what to click, where, etc to recreate the issue.

Thanks,
Dan

**Comment by danbucholtz** [comment]
Hi @louisdoe - we're going to close this due to lack of response.  If you do respond and provide instructions, we'll re-open and take a look.  Thanks for contributing and for using Ionic!

Thanks,
Dan
