### ISSUE TITLE
docs: ion-slide-pager and ion-slide links don't work

### ISSUE THREAD

**Issue by jonmarinello** [driftyco/ionic#4700]
**Type**: <span ionic-type>docs</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>The ion-slide-pager and ion-slide links don't work and result in GET errors on your website. I'm trying to get sliders working and I need access to this documentation.</span>

<span is-issue-template></span>

**Comment by jonmarinello** [comment]
Example error: `Cannot GET /docs/nightly/api/directive/ionSlidePager/`

**Comment by mhartington** [comment]
There is no ion-slide-pager directive
https://github.com/driftyco/ionic/blob/master/js/angular/directive/slideBox.js

**Comment by jonmarinello** [comment]
I'm referring to the two links on http://ionicframework.com/docs/nightly/api/directive/ionSlideBox/. See below ( ion-slide-pager and ion-slide)

![screen shot 2015-12-03 at 9 51 56 am](https://cloud.githubusercontent.com/assets/1432192/11568914/b539912e-99a3-11e5-8e2f-9d607c90bd4f.png)

**Comment by jonmarinello** [comment]
@mhartington: can this be re-opened and fixed?

**Comment by mhartington** [comment]
This has been fixed. The links have been removed. There is no pager directive, so all is well

**Comment by jonmarinello** [comment]
Great thanks much!

**Comment by jonmarinello** [comment]
Problem is back again on the live site.

See http://ionicframework.com/docs/nightly/api/directive/ionSlideBox/
