### ISSUE TITLE
bug: iOS white screen after keyboard show (in v1.2.1 and v1.2.0 only)

### ISSUE THREAD

**Issue by DanailMinchev** [driftyco/ionic#4849]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>8</span>  <span ionic-webview>webview</span>

<span ionic-description>

Hi,

The bug is reproducible with latest ionic releases **1.2.1** and **1.2.0**, but not with **1.1.1**.
In **1.1.1** it works fine.

On iOS, when I tap on some html input:

- The keyboard is shown - OK:
![photo 22-12-2015 14 23 14](https://cloud.githubusercontent.com/assets/7883702/11957247/913bf9be-a8b8-11e5-982d-b7f2281fb738.png)

- I can enter some text and select another inputs (but without closing the keyboard dialog) - OK
![photo 22-12-2015 14 24 06](https://cloud.githubusercontent.com/assets/7883702/11957264/ad1f5518-a8b8-11e5-9bfe-1b0371f97b74.png)

- Once the keyboard is closed (either with `Done` button or just by tapping to non-input space) - the inputs with their labels become white, but I can still type into inputs with white font - so it looks like white screen which overlays the content.
![photo 22-12-2015 14 24 51](https://cloud.githubusercontent.com/assets/7883702/11957266/b4373bc2-a8b8-11e5-9a7d-79fe042a842b.png)
![photo 22-12-2015 14 24 55](https://cloud.githubusercontent.com/assets/7883702/11957269/b8134cea-a8b8-11e5-8b5d-6bd3743edf0c.png)

Code example:
```
<ion-view view-title="Log In" can-swipe-back="false" hide-back-button="true">
  <ion-content padding="true" has-bouncing="false">
    <form ng-submit="vm.loginFormAction(vm.loginFormData)" novalidate>
      <div class="list">
        <label class="item item-input item-floating-label">
          <span class="input-label">Username</span>
          <input ng-model="vm.loginFormData.username" type="text" placeholder="Email or Phone number">
        </label>
        <label class="item item-input item-floating-label">
          <span class="input-label">Password</span>
          <input ng-model="vm.loginFormData.password" type="password" placeholder="Password">
        </label>
      </div>
      <div class="padding">
        <button class="button button-block button-positive" type="submit">Log In</button>
      </div>
    </form>
  </ion-content>
</ion-view>
```

also I've tried with the new **ion-input** directive:
```
<ion-view view-title="Log In" can-swipe-back="false" hide-back-button="true">
  <ion-content padding="true" has-bouncing="false">
    <form ng-submit="vm.loginFormAction(vm.loginFormData)" novalidate>
      <div class="list">
        <ion-input class="item item-input item-floating-label">
          <ion-label>Username</ion-label>
          <input ng-model="vm.loginFormData.username" type="text" placeholder="Email or Phone number">
        </ion-input>
        <ion-input class="item item-input item-floating-label">
          <ion-label>Password</ion-label>
          <input ng-model="vm.loginFormData.password" type="password" placeholder="Password">
        </ion-input>
      </div>
      <div class="padding">
        <button class="button button-block button-positive" type="submit">Log In</button>
      </div>
    </form>
  </ion-content>
</ion-view>
```

`ionic info`
```
Your system information:

Cordova CLI: 5.4.1
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.2.1-nightly-1867
Ionic CLI Version: 1.7.12
Ionic App Lib Version: 0.6.5
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04 LTS 
Node Version: v5.0.0
```

`ionic platform ls`
```
Updated the hooks directory to have execute permissions
Installed platforms: android 5.0.0, ios 3.9.2
Available platforms: amazon-fireos, blackberry10, browser, firefoxos, ubuntu, webos
```

`config.xml`
```
  <preference name="HideKeyboardFormAccessoryBar" value="false"/>
  <preference name="KeyboardDisplayRequiresUserAction" value="false"/>
  <preference name="SuppressesLongPressGesture" value="true"/>

  <plugin name="ionic-plugin-keyboard" spec="1.0.8"/>
```

`bower.json`
```
"ionic": "driftyco/ionic-bower#1.2.1"
"ionic-platform-web-client": "0.2.1"
```

</span>

<span is-issue-template></span>

**Comment by Ionitron** [comment]
Greetings @DanailMinchev!

My sensors indicate that you need to update your issue through our [custom issue form](http://ionicframework.com/submit-issue/#/?iid=4849). We are now requiring all issues to be submitted this way, to ensure that we have all of the information necessary to fix them as quickly as possible.

**[Click Here To Update Your Issue](http://ionicframework.com/submit-issue/#/?iid=4849)**

I will have no choice but to close this issue if it is not resubmitted through the form. Please fill out the rest of the form, so that I may use my friendly robot powers to assist you.

Thank you!

<span ionitron-issue-resubmit></span>

**Comment by mlynch** [comment]
Hmm, not able to reproduce on iOS 9. Can you try this app and let me know what you see in the first dashboard tab with the keyboard?

http://ionic-io-assets.s3.amazonaws.com/pp2.tar.gz

**Comment by DanailMinchev** [comment]
The result is the same as with my original app ..

- The initial screen (no tapping / action) - OK
![photo 22-12-2015 17 12 54](https://cloud.githubusercontent.com/assets/7883702/11961338/bdb28afa-a8cf-11e5-8f56-90cf5f49d090.png)

- On `Email or Phone Number` input tapping - OK
![photo 22-12-2015 17 13 16](https://cloud.githubusercontent.com/assets/7883702/11961353/dade45b0-a8cf-11e5-8c90-225afbabab4a.png)

-  On `Email or Phone Number` texting "Test" - OK
![photo 22-12-2015 17 13 29](https://cloud.githubusercontent.com/assets/7883702/11961358/e295dd68-a8cf-11e5-9ef2-fb8f8992d2ee.png)

- After tapping on the second input `Password` - white screen after quick blinking
![photo 22-12-2015 17 13 39](https://cloud.githubusercontent.com/assets/7883702/11961391/233d11c4-a8d0-11e5-85df-e13157fc4523.png)
![photo 22-12-2015 17 13 50](https://cloud.githubusercontent.com/assets/7883702/11961396/278f7078-a8d0-11e5-9a6a-84007f0bc7e5.png)

I am using:
```
iPhone 4s
iOS 9.2 (13C75)
Xcode 7.1
xcodebuild -showsdks -> iOS 9.1
```

**Comment by Emeryao** [comment]
+1

**Comment by Lsozke** [comment]
+1 in iOS 9.2 / iPhone 6s
Temporary solved by replacing `<ion-content>` with `<ion-scroll>`
```
<ion-scroll direction="y" style="right: 0;bottom: 0;left: 0;position: absolute;" class="has-header has-subheader">
```

**Comment by RBLU** [comment]
I had the same. Reproducible in IOS Simulator iPhone 5s with IOS 9.2, but not with iPhone 6.
Temporary workaround is to set overflow-scroll to false on ion-content.

**Comment by andreialecu** [comment]
+1 seeing this with wkwebview

**Comment by leschirmeur** [comment]
Seems to be the same issue as https://github.com/driftyco/ionic/issues/4645 where I added quite an extensive comment: https://github.com/driftyco/ionic/issues/4645#issuecomment-165884959

Our temporary workaround is to set overflow-y to hidden whenever a keyboard transition starts and to set it back to scroll whenever a keyboard transition has ended. Having this in place, the blank screen issue seems not to occur anymore. However, this should be temporary only.

**Comment by albertytau** [comment]
Yes, temporary downgrade to 1.1.1 to avoid this bug

**Comment by mlynch** [comment]
Do you guys have the `ionic-plugin-keyboard` plugin installed? I was only able to reproduce this without the plugin installed, which is expected. The keyboard plugin is required for proper keyboard behavior

**Comment by mlynch** [comment]
Okay, it seems to fail when using the accessory bar with the keyboard plugin. One solution is to not use it (which is more native like anyways). Looking into fixing this.

**Comment by mlynch** [comment]
Err, not quite resolved just yet, need to reset something

**Comment by Emeryao** [comment]
I haven't used the keyboard plugin but it dosen't work either

**Comment by andreialecu** [comment]
I cannot use `ionic-plugin-keyboard` because it is broken with [WKWebView](https://github.com/Telerik-Verified-Plugins/WKWebView). Meaning the accessory bar cannot be hidden and it doesn't disable scroll either. 

[cordova-plugin-keyboard](https://github.com/cjpearson/cordova-plugin-keyboard/commit/33cbbd9c5b93ba5a1d4be8ff19f8fa8b5f76c2f0) works as per this commit.

**Comment by mlynch** [comment]
Okay, just pushed a fix for this to master. Can you try and let me know? 

I suppose we'll need to update our plugin for wkwebview. The major important point is that disable scroll has to be set to true on the web view if you want normal behavior. If you're not using WKWebView, you will want to use `ionic-plugin-keyboard` for your app.

**Comment by leschirmeur** [comment]
Thanks @mlynch for the fix. I'll try it in a couple of days, off for New Years right now. We are using the keyboard plugin but not WKWebView.

**Comment by DanailMinchev** [comment]
@mlynch 

I can confirm that it's working with my configuration:
- iOS 3.9.2
- ionic-plugin-keyboard 1.0.8

Thank you!

**Comment by leschirmeur** [comment]
@mlynch Confirm that no blank screens occur anymore in our setup using 1.2.2.

**Comment by mlynch** [comment]
@leschirmeur thanks. Thinking of going back to JS scrolling for iOS given a number of issues we're discovering now. Want to apologize to everyone for the QA issues in this recent release.

**Comment by mazagatshy** [comment]
the problem exists with (select),
I have the same problem when taping on the screen to hide the select menu, the screen became white this invisible components
![simulator screen shot 1 feb 2016 11 44 55](https://cloud.githubusercontent.com/assets/4346191/12712440/742f62a2-c8d9-11e5-8afd-20d1f81cd964.png)
![simulator screen shot 1 feb 2016 11 46 06](https://cloud.githubusercontent.com/assets/4346191/12712441/743d610e-c8d9-11e5-83c2-12672e6e92bb.png)

**Comment by mazagatshy** [comment]
using ion-scroll instead of ion-content solve the problem

**Comment by mohanchalla** [comment]
In My Case also the input labels are getting hidden by the keyboard in ios.

**Comment by salihklc** [comment]
Yes using ion-scroll instead of ion-content solve the problem but in my case I have fixed footer button in ion-footer-bar which is outside of ion-scroll but in the ion-view. I want to hide that footer when the keyboard opened but native.keyboardshow event not firing [#33](https://github.com/driftyco/ionic-plugin-keyboard/issues/33) . I don't want to write hard code event listener on focus or blur event for hide and show footer. Any opinion will be helpful thanks..

**Comment by mohanchalla** [comment]
If I use ion-scroll it showing white screen at the bottom of the screen.

**Comment by ghadeerrahhal** [comment]
@mohanchalla I had the same problem. If you add 

<code> height: 100% </code> to 
<code> scroll-view.scroll-y classes </code>

The white part at the bottom should go away.

**Comment by mohanchalla** [comment]
@ghadeerrahhal Thank you for your suggestion. I fixed this issue by using ion-scroll and style="position: absolute".

**Comment by salihklc** [comment]
I solve the issue besides I use ion-content. In my case all problem caused by has-footer, I remove the has-footer class when keyboard shown and add it back when keyboard hide. 
` window.addEventListener('native.keyboardshow', function () {
      document.body.classList.add('keyboard-open');
      var content = angular.element(document.getElementById($state.current.name));
      content.removeClass("has-footer");
    });

    window.addEventListener('native.keyboardhide', function () {
      var content = angular.element(document.getElementById($state.current.name));
      content.addClass("has-footer");
    }); `
I gave id on my all ion-content same as they route name like you see. For more detail write comment. 
PS: After all , I realise [this](https://forum.ionicframework.com/t/white-space-above-keyboard-or-select-box-control-pic-inside/4580/16) topic also related to my problem. Another approach.

**Comment by ghadeerrahhal** [comment]
@salihklc I had the same problem on another view where the keyboard coming up. See if this fix works for you (much less verbose)

<code>
document.getElementById("YOUR_CONTENT_ID").style.height = "100%"
<code/>

**Comment by dwilt** [comment]
Had this issue as well. Converted `ion-content` to an `ion-scroll` and it fixed the issue. Thank you @Lsozke. 

I've also noticed that the content pops back if you toggle any CSS property within the developer tools. It seems to be some kind of repaint issue.

**Comment by dwilt** [comment]
FYI, I had to revert the `ion-scroll` solution because `ion-scroll` introduces other problems with form elements and the keyboard.

**Comment by atul-athawale** [comment]
I had same issue.I replaced my view in this way.
<ion-nav-view>
  <ion-view>
    <ion-content>
      Hello!
    </ion-content>
  </ion-view>
</ion-nav-view>

I found out that I missed <ion-view> in my sub template.
After adding <ion-view> issue was fixed.
For reference.
http://ionicframework.com/docs/api/directive/ionView/

**Comment by bent0b0x** [comment]
Is there a fix for the white screen issue? I still see it with this configuration:

ionic —version: 1.7.14
ionic.version: 1.2.4-nightly-1917
iOS: 9.2.1
I am using the ionic keyboard plugin

ion-nav-view
  ion-view
    ion-content (overflow-scroll="true")
      ion-scroll

When the keyboard is up, and the user does any scrolling, then dismisses the keyboard, the whole ion-view goes white until the user taps again.

If I use this view structure: 

ion-nav-view
  ion-view
    ion-content (no overflow-scroll)
      ion-scroll

Then when an input gains focus the entire nav view jumps down and then back up. The screen going white, on the other hand, no longer happens.

**Comment by anasbud** [comment]
I have the same issue. Overflow-scroll didn't fix it :(

Any solution ?

**Comment by salihklc** [comment]
Hi,
here what I did for solution
**Keyboard Configuration (I write this code in the [angular module run function](https://docs.angularjs.org/guide/module) )**
```js
if (window.cordova && window.cordova.plugins.Keyboard) {
        if (isIOS) cordova.plugins.Keyboard.disableScroll(true);
        cordova.plugins.Keyboard.hideKeyboardAccessoryBar(false);
      }
      if (window.StatusBar) {
        StatusBar.styleDefault();
      } 
```
This code (above) is my keyboard configuration and after I add an event listener for keyboard show event (below), like you see in the code I catch current state name which is also my ion-content id. For example if my state define like `myapp.state('contact', {
        cache: false,
        url: '/contact',
        templateUrl: 'templates/contact.html',
        controller: 'ContactCtrl'
      }) `  this then I add id on my ion-content (in contact.html) like `<ion-content id="contact"> ... </ion-content> `

** Event Listener Code (I write this code in the [angular module run function](https://docs.angularjs.org/guide/module) ):**
```js
window.addEventListener('native.keyboardshow', function () {
      document.body.classList.add('keyboard-open');
      var content = angular.element(document.getElementById($state.current.name));
      content.removeClass("has-footer");
      console.log(document.body.classList);
    });
```

```js
window.addEventListener('native.keyboardhide', function () {
      var content = angular.element(document.getElementById($state.current.name));
      content.addClass("has-footer");
      document.body.classList.remove('keyboard-open');
      console.log(document.body.classList);
    });
```

Let me notice if it's not work.
Sorry for my super awesome english.

**Comment by VinceOPS** [comment]
Still having this issue using `ion-content` and ionic 1.3, iOs 9.2 on an iPhone 6

**Comment by ghadeerrahhal** [comment]
Does this work?

```
<ion-content has-bouncing="false" scroll="false">
```

**Comment by VinceOPS** [comment]
The issue is: I **need** the scrolling feature. Setting `overflow-y` as `hidden` or disabling scroll is not possible...

**Comment by leschirmeur** [comment]
@VinceOPS Have you tried these 2 solution proposals from above yet?
1) https://github.com/driftyco/ionic/issues/4849#issuecomment-177859726
2) https://github.com/driftyco/ionic/issues/4849#issuecomment-182915560

If not, maybe the below code snippet which shows a directive function we are using to circumvent the blank screen issue works for you as well..

    /* @ngInject */
    function qyToggleOverflowScroll($timeout, $window, qyIonicReady) {
        var directive = {
            restrict: 'A',
            link: link
        };
        return directive;

        function link(scope, element, attrs) {
            var domElement = element[0];

            qyIonicReady().then(function onQyIonicReady() {
                $window.addEventListener('native.keyboardshow', handleKeyboardShow);
                $window.addEventListener('native.keyboardhide', handleKeyboardHide);

                // remove event listener on destroy
                scope.$on('$destroy', removeKeyboardHandlerListener);

                function handleKeyboardShow() {
                    console.log('qyOverflowScrollToggle keyboard show: ELEMENT CLASS LIST: '
                        + domElement.classList.toString());
                    // iOS or Android full screen
                    var isIosOrAndroidFullScreen
                        = Config.OS.isIOS || (Config.OS.isAndroid && ionic.Platform.isFullScreen);

                    if (isIosOrAndroidFullScreen) {
                        // wrap in timeout to avoid screen flicker
                        //$timeout(function () {
                        console.log('qyOverflowScrollToggle: '
                            + 'keyboard is shown, set overflow-y to: scroll');
                        domElement.style.overflowY = 'hidden';
                        //element.css('overflow-y', 'hidden');
                        //element.css('-webkit-overflow-scrolling', 'auto');
                        //});

                        $timeout(function setOverflowYToScrollIfNeeded() {
                            var scrollerHeight = element.height();
                            var scrollerContentHeight = domElement.scrollHeight;

                            // if scroller contains enough content to enable scrolling
                            if (scrollerContentHeight > scrollerHeight + 1) {
                                console.log('qyOverflowScrollToggle keyboard show: '
                                            + 'scroller height / scroller content height: '
                                            + scrollerHeight
                                            + ' / '
                                            + scrollerContentHeight);

                                console.log('qyOverflowScrollToggle keyboard show: '
                                            + 'content larger than scroller, set overflow-y to: scroll');
                                domElement.style.overflowY = 'scroll';
                                //element.css('overflow-y', 'scroll');
                                //element.css('-webkit-overflow-scrolling', 'touch');
                            }
                        }, 400);
                    }
                }

                function handleKeyboardHide() {
                    console.log('qyOverflowScrollToggle keyboard hide: ELEMENT CLASS LIST: '
                        + domElement.classList.toString());
                    //// iOS or Android full screen
                    var isIosOrAndroidFullScreen
                        = Config.OS.isIOS || (Config.OS.isAndroid && ionic.Platform.isFullScreen);

                    if (isIosOrAndroidFullScreen) {
                        // wrap in timeout to avoid screen flicker
                        //$timeout(function () {
                        element.css('overflow-y', 'hidden');
                        element.css('-webkit-overflow-scrolling', 'auto');
                        //});

                        $timeout(function setOverflowYToScrollIfNeeded() {
                            //var scrollerHeight = element.height();
                            var scrollerHeight = domElement.clientHeight;
                            var scrollerContentHeight = domElement.scrollHeight;

                            console.log('qyOverflowScrollToggle keyboard hide: '
                                + 'scroller height / scroller content height: '
                                + scrollerHeight
                                + ' / '
                                + scrollerContentHeight);

                            // if scroller contains enough content to enable scrolling
                            if (scrollerContentHeight > scrollerHeight + 1) {
                                console.log('qyOverflowScrollToggle keyboard hide: '
                                    + 'content larger than scroller, set overflow-y to: scroll');
                                element.css('-webkit-overflow-scrolling', 'touch');
                                element.css('overflow-y', 'scroll');
                            }
                        }, 400);
                    }
                }

                function removeKeyboardHandlerListener() {
                    $window.removeEventListener('native.keyboardshow', handleKeyboardShow);
                    $window.removeEventListener('native.keyboardshow', handleKeyboardHide);
                }
            });
        }
    }


It might also help you looking at my comment to another issues some time ago here: https://github.com/driftyco/ionic/issues/4645#issuecomment-165884959

**Comment by VinceOPS** [comment]
@leschirmeur Hi! Thanks for your help! I ended doing something else: I fixed the "bottom" positioning of my elements (the same which were disappearing). It's quite fine is my context/layout.

**Comment by shivenigma** [comment]
This issue is driving me crazy, How did the team let this issue without fixing this at first hand. I made ugly hacks and those hacks affecting other parts of my app in android and ios. I am going to think about using ionic in my next app, its features are great but have fundamental flaws like this.

**Comment by leschirmeur** [comment]
@shivenigma Try the directive I posted above on the <ion-content> element. It's working quite well for us, no blank screen issues anymore. Pasting updated code below, which removes screen flicker when hiding keyboard.

```
angular
        .module('quiply')
        .directive('qyToggleOverflowScroll', qyToggleOverflowScroll);

/* @ngInject */
    function qyToggleOverflowScroll($timeout, $window, qyIonicReady) {
        var directive = {
            restrict: 'A',
            link: link
        };
        return directive;

        function link(scope, element, attrs) {
            var domElement = element[0];

            qyIonicReady().then(function onQyIonicReady() {
                $window.addEventListener('native.keyboardshow', handleKeyboardShow);
                $window.addEventListener('native.keyboardhide', handleKeyboardHide);

                // remove event listener on destroy
                scope.$on('$destroy', removeKeyboardHandlerListener);

                function handleKeyboardShow() {
                    console.log('qyOverflowScrollToggle keyboard show: ELEMENT CLASS LIST: '
                        + domElement.classList.toString());
                    // iOS or Android full screen
                    var isIosOrAndroidFullScreen
                        = Config.OS.isIOS || (Config.OS.isAndroid && ionic.Platform.isFullScreen);

                    if (isIosOrAndroidFullScreen) {
                        console.log('qyOverflowScrollToggle: '
                            + 'keyboard is shown, set overflow-y to: scroll');
                        domElement.style.overflowY = 'hidden';
                        // set -webkit-overflow-scrolling to auto for having non-momentum scrolling if
                        // keyboard is up. Setting it to touch causes screen flicker when closing keyboard
                        domElement.style.webkitOverflowScrolling = 'auto';

                        $timeout(function setOverflowYToScrollIfNeeded() {
                            var scrollerHeight = element.height();
                            var scrollerContentHeight = domElement.scrollHeight;

                            // if scroller contains enough content to enable scrolling
                            if (scrollerContentHeight > scrollerHeight + 1) {
                                console.log('qyOverflowScrollToggle keyboard show: '
                                            + 'scroller height / scroller content height: '
                                            + scrollerHeight
                                            + ' / '
                                            + scrollerContentHeight);

                                console.log('qyOverflowScrollToggle keyboard show: '
                                            + 'content larger than scroller, set overflow-y to: scroll');
                                domElement.style.overflowY = 'scroll';
                                // no need to set -webkit-overflow-scrolling as it should remain with value auto
                                // whenever keyboard is up. We disable momentum scrolling when keyboard is up.
                            }
                        }, 400);
                    }
                }

                function handleKeyboardHide() {
                    console.log('qyOverflowScrollToggle keyboard hide: ELEMENT CLASS LIST: '
                        + domElement.classList.toString());
                    //// iOS or Android full screen
                    var isIosOrAndroidFullScreen
                        = Config.OS.isIOS || (Config.OS.isAndroid && ionic.Platform.isFullScreen);

                    if (isIosOrAndroidFullScreen) {
                        domElement.style.overflowY = 'hidden';
                        // set -webkit-overflow-scrolling to auto for keyboard transition
                        domElement.style.webkitOverflowScrolling = 'auto';

                        $timeout(function setOverflowYToScrollIfNeeded() {
                            var scrollerHeight = domElement.clientHeight;
                            var scrollerContentHeight = domElement.scrollHeight;

                            console.log('qyOverflowScrollToggle keyboard hide: '
                                + 'scroller height / scroller content height: '
                                + scrollerHeight
                                + ' / '
                                + scrollerContentHeight);

                            // if scroller contains enough content to enable scrolling
                            if (scrollerContentHeight > scrollerHeight + 1) {
                                console.log('qyOverflowScrollToggle keyboard hide: '
                                    + 'content larger than scroller, set overflow-y to: scroll');
                                domElement.style.overflowY = 'scroll';
                                // set -webkit-overflow-scrolling to touch for default momentum scrolling if
                                // keyboard is not up
                                domElement.style.webkitOverflowScrolling = 'touch';
                            }
                        }, 400);
                    }
                }

                function removeKeyboardHandlerListener() {
                    $window.removeEventListener('native.keyboardshow', handleKeyboardShow);
                    $window.removeEventListener('native.keyboardhide', handleKeyboardHide);
                }
            });
        }
    }
```

**Comment by shivenigma** [comment]
@leschirmeur  on which element I should use this directive? ion-content?

**Comment by leschirmeur** [comment]
@shivenigma yes

**Comment by zanemcca** [comment]
I tried @leschirmeur solution but it did not work for me.
@mlynch Can this issue please be reopened because it is definitely not fixed. This makes for a very poor UX which should give it some priority but it seems to be ignored.

I think it is likely related to this [issue](https://github.com/driftyco/ionic-plugin-keyboard/issues/168) in `ionic-plugin-keyboard`.

**Comment by shivenigma** [comment]
Unknown provider: qyIonicReadyProvider <- qyIonicReady <- qyToggleOverflowScrollDirective

is there something you missed to give me.? @leschirmeur

**Comment by leschirmeur** [comment]
@shivenigma qyIonicReady is just a service wrapping $ionicPlatform.ready(). So you might just use this ready() function instead of the service. However, if you want to go for the service, here it is:

```
angular
        .module('quiply')
        .factory('qyIonicReady', qyIonicReady);

    /**
     * Workaround for silently ignored callbacks.
     *
     * Details see http://stealthcode.co/multiple-calls-to-ionicplatform-ready/
     */
    /* @ngInject */
    function qyIonicReady($ionicPlatform) {
        var readyPromise;

        return function () {
            if (!readyPromise) {
                readyPromise = $ionicPlatform.ready();
            }
            return readyPromise;
        };
    }
```

**Comment by shivenigma** [comment]
sorry to disturb you again, but I am totally new to ionic and can't get this directive to work. I am getting the following error.
 

> Can't find variable: Config

what is Config, is it ionic default or something you wrote for yourself? @leeschmidt4

**Comment by leschirmeur** [comment]
@shivenigma Just replace the Config.xxx statements with functions offered by ionic.Platform (http://ionicframework.com/docs/api/utility/ionic.Platform/).

**Comment by shivenigma** [comment]
@leeschmidt4 Thanks for your patience and kindness for helping me, you saved me from lot of the work I have to do in order to solve this issue, If you could make it as an individual directive and release it as a support for ionic, I'll be glad to contribute and improve if there are anyways to help you. Considering making this as an individual directive without your internal dependencies, I think lot of people needs this. Thanks a ton buddy, I solved the issue, If you have any known side effects of this please let me know. Thanks again.

**Comment by lucasarts321** [comment]
@leschirmeur i love you bro thanks works like a charm; own you a beer !

**Comment by leschirmeur** [comment]
Glad to hear that, @lucasarts321 :-)

**Comment by mbcooper** [comment]
My main view has <ion-side-menus as their root elements ...

I get an error:
`TypeError: o.height is not a function. (In 'o.height()', 'o.height' is undefined) (caused by "undefined")`

when I  use the qyToggleOverflowScroll directive.

**Comment by leschirmeur** [comment]
@mbcooper Are you using jQuery? I guess not, the directive code requires jQuery to work. Otherwise you'd need to modify according to your needs...

**Comment by mbcooper** [comment]
ugh

**Comment by anilking** [comment]
it will avid the blank or white screen 

add this two attributes to ion-content  padding="true" overflow-scroll="false"  

it is working for me

**Comment by edesaintchamas** [comment]
The blank screen come from an css redraw issue apparently.

We have found a quick workaround: we have created a directive that forces the browser to redraw the element every 30ms. When applying the directive to `ion-content` it fixes the issue.

Here is the directive:

	var app = angular.module('myapp');
	app.directive('keyboardCssRedraw', function($interval, $window, $state){
		return {
			restrict: 'A',
			link: link
		};

		function link(scope, element, attrs) {
			var interval = setInterval(function(){
				redraw(element[0]);
			}, 30);
			scope.$on('$destroy', function(){
				clearInterval(interval);
			});
		}

		// force redraw
		function redraw(element) {
			element.style.zIndex = 1;
			element.offsetHeight;
			element.style.zIndex = '';
		}
	});

Apply directive:

`<ion-content keyboard-css-redraw>`

This solution is a bit dirty as we constantly redraw the element. As it seems we have tackle the issue, it would be great if some ionic expert could help rewriting this code in a more "ionic" way :)

**Comment by demirag** [comment]
After a long nightmares, in version 1.3.1, adding "overflow-scroll="false" to <ion-content> elements fixed almost all my problems.

**Comment by demirag** [comment]
After a long nightmares, in version 1.3.1, adding `overflow-scroll="false"` to `<ion-content>` elements fixed almost all my problems.

**Comment by DanielWSP** [comment]
Thank you @demirag this saved the day!

**Comment by nstokoe** [comment]
Bug is definitely still in ionic 1.3.

I didn't want to have to set overflow-scroll false on all my ion-content elements or use the ionicConfigProvider to disable native scroll (since js scrolling has other issues), so I just added back this snippet of css that was removed in 1.3.0 https://github.com/driftyco/ionic/commit/aec6598d:

```
.overflow-scroll {
  &.keyboard-up:not(.keyboard-up-confirm) {
    overflow: hidden;
  }
}
```

**Comment by VinceOPS** [comment]
@nstokoe I got this issue again on iOs today, and went back on this thread. Found your proposition. It worked. Thanks :).

**Comment by ScottTheriault** [comment]
I know I am a little late, but here's my two cents.

turning off overflow-scroll seamed to work, but I prefer keeping the native scrolling on.

So I did something similar to @edesaintchamas but used [ionic-plugin-keyboard](https://github.com/driftyco/ionic-plugin-keyboard) to make it a bit more efficient


    redrawState: function() {
        stateId = $ionicHistory.currentView().stateId;
        element = $("[state='" + stateId + "'] ion-content")[0];

        element.style.zIndex = 1;
        element.offsetHeight;
        element.style.zIndex = '';
    }
    
    window.addEventListener('native.keyboardshow', redrawState);
    window.addEventListener('native.keyboardhide', redrawState);`

And yes, I know you shouldn't use jQuery with ionic, but it is what it is.

**Comment by Khrystyna** [comment]
Still reproducible for me. Thanks @Lsozke for solution! Replacing `<ion-content>` with `<ion-scroll>` works.  Though, I had to add also class `"hide-on-keyboard-open"` to elements above my textarea to fit it into screen while typing as keyboard takes half of a screen.

**Comment by udithaPS** [comment]
Solved by replacing <ion-content> with <ion-scroll>

**Comment by udithaPS** [comment]
Temporary solved by replacing `<ion-content>` with `<ion-scroll>`

**Comment by sryze** [comment]
Bug still exists in Ionic 1.3.1 on iOS 10.2. Android works ok.

**Comment by sryze** [comment]
@ScottTheriault's solution worked for me, though I had to replace `$("[state='" + stateId + "'] ion-content")[0]` with `$("ion-content")[0]`.

**Comment by almothafar** [comment]
Bug still exists in Ionic 1.3.2 for iOS 9 and 10, Android is working good.

**Comment by almothafar** [comment]
@mlynch may you re-open this please?

**Comment by gregor-srdic** [comment]
I also have this problem in iOs with ionic 1, overflow-scroll="true" on ion-content helps, 
but then the min-height=100% does not work, so I can not position the form in the middle of the screen :S

**Comment by VinceOPS** [comment]
This bug still exists on iOS 10.2+ and ionic 1.3.2, when using Native scrolling (`overflow-scroll` set to `true`, or JS Scrolling globally disabled).

Inspired by @nstokoe 's suggestion:
```
.overflow-scroll {
  &.keyboard-up:not(.keyboard-up-confirm) {
    -webkit-overflow-scrolling: auto;
  }
}
```

It solves the issue, the same way, but does not "block" scrolling (`overflow: hidden` does prevent from scrolling). To be more specific, here the user can scroll if he does not focus keyboard inputs.

In `scrollViewNative.js` (ionic v1), you can see this at two different places (keyboard opening and keyboard closing): 
```
/*
              if (ionic.Platform.isIOS()) {
                // Force redraw to avoid disappearing content
                var disp = container.style.display;
                container.style.display = 'none';
                var trick = container.offsetHeight;
                container.style.display = disp;
              }
              */
```

I assume it has been left commented/unused because this bug can still cause Crashes, even if forced-redrawing almost "hides" it (it does not avoid flickering). I didn't have a look at the keyboard plugin code, but I guess that something is wrong inside, if the app crashes.

**Comment by ugosan** [comment]
I've figured out that in the case of our app, what was triggering this behaviour was a swipe gesture, so adding `$ionicConfigProvider.views.swipeBackEnabled(false);` solved for us.

**Comment by rkaveski** [comment]
I did a workaround that has worked for me:

CSS:
```
.platform-ios div.scroll {
    height: 101%;
}
```

View:
`<ion-content scrollbar-y="false">`

Seems like `<ion-content>` needs his content to overflow. I inserted a lot of `<p>Lorem Ipsum</p>`, then I cleared the CSS rule and everything works fine, because the `<p>` sequence causes the content overflow.

**Comment by atasciuc** [comment]
From my research it looks that all of this related with the keyboard transition. When elements have absolute positioning and -webkit-transform: translate3d(0,0,0); set while keyboard is animated the z-index gets messed up. Transform is used to kick the GPU for transitions. For more info look here: [here](http://stackoverflow.com/questions/10814178/css-performance-relative-to-translatez0). By removing transform everything works as expected.

**Comment by VinceOPS** [comment]
I finally got this fixed/working on iOS using **native scrolling**  and forcing the position of modal-backdrop (the parent of any modal container) to `absolute` instead of `fixed`.

```
@media (max-width: $modal-inset-mode-break-point - 1) {
    .modal-backdrop.active {
        position: absolute !important;
    }
}
```

The media-query is made for everything beyond the resolution which is considered as a Tablet, leading to inset/centered modal (currently 680px, by default, in _variables.scss). In that case, Smartphones.
I only target .active modal as the other one are not visible, thus, not relevant.

**Comment by niyando** [comment]
I had this issue with native scrolling and found that it was limiting the height of the ion-content whenever the keyboard was up. This caused my view to appear truncated (half blank) unless you close the keyboard. I solved it by force setting the height to auto. Hope this helps.

```css
.keyboard-up{
  height: auto !important;
}
```

**Comment by kchahiyodotcom** [comment]
if you are using only <ion-content>....</ion-content> add <ion-scroll> in it like so,
<ion-content><ion-scroll>...</ion-scroll></ion-content> this solved my issue.

**Comment by kchahiyodotcom** [comment]
adding ion-scroll inside ion-content solved my issue

**Comment by glemiere** [comment]
Hey!
Just in case someone runs into this issue (it can happens with ionic 1, 2, and even 3), the proper way to fix it is to remove cordova-plugin-keyboard, and installing ionic-plugin-keyboard instead.

Enjoy!

**Comment by mspado** [comment]
@glemiere Are you sure thats all you changed? I'm having the issue with the viewport not resizing back to original size after the keyboard is closed. Have completely uninstalled and removed cordova-plugin-keyboard and only ionic keyboard is in there. Still having the issue.

Whereas if I install the 'tabs' default app it works perfectly with the keyboard.

**Comment by mspado** [comment]
Hi,

I found the cause of this *very* frustrating issue for me was:
```
this.statusBar.overlaysWebView(false);
```

...that's it. Just make sure you don't call that.

**Comment by dogindot** [comment]
Removing `-webkit-overflow-scrolling: touch;` or set it to `auto` was fixing this behavior. 
Since it was only occurring on the login page, setting this style especially for the login view was helping me.

**Comment by adamsolomon1986** [comment]
Hope this helps anyone. In my case, I just set the footer background to the ion-content background color and the issue disappeared
