### ISSUE TITLE
bug: ion-slides slider undefined in modal

### ISSUE THREAD

**Issue by rushtehrani** [driftyco/ionic#4876]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Setting a `$scope.watch` on `slider` doesn't seem to work when ion-slider is in a modal.   

See console in [this CodePen](http://codepen.io/anon/pen/YwpeRE)</span>

<span is-issue-template></span>

**Comment by mlynch** [comment]
Was fixed tonight, check out master or a nightly, thanks!

**Comment by rushtehrani** [comment]
The CodePen is using nightly and I'm using master locally but I am still seeing the issue.

**Comment by mlynch** [comment]
Okay, must be a different issue. Thanks!

**Comment by jgw96** [comment]
This issue was moved to driftyco/ionic-v1#30
