### ISSUE TITLE
bug: $ionicScrollDelegate.freezeScroll doesn't work

### ISSUE THREAD

**Issue by JerryBels** [driftyco/ionic#4885]
**Type**: <span ionic-type>bug</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>Hello,

$ionicScrollDelegate.freezeScroll doesn't work at all. No error in the console, it simply won't work.

http://codepen.io/JerryBels/pen/MKbNOV?editors=101

It doesn't help to use `$getByHandle`.</span>

<span is-issue-template></span>

**Comment by mlynch** [comment]
Fixed recently, will be out in next release

**Comment by JerryBels** [comment]
Hey @mlynch , thanks ! Could I know about when it can be expected for release ? My app relies on this and I'm in the process of releasing it to the app store and Google Play !

**Comment by JerryBels** [comment]
@mlynch I just installed 1.2.4 on my project, it seems to revert back IOS to JS scrolling which fix the issue for IOS, but the issue is still present for Android using native scrolling.

**Comment by flavordaaave** [comment]
It is possible to disable/enable scrolling in native scrolling by dynamically changing the the CSS rule for the scroll are from:
`overflow-y: scroll;` (scrolling enabled) to `overflow-y: hidden;` (scrolling blocked)

@mlynch perhaps this might be useful for $ionicScrollDelegate.freezeScroll in future releases

**Comment by JerryBels** [comment]
Thanks @flavordaaave I was going to add this. +1 for the suggestion.
