### ISSUE TITLE
bug: After keyboard open, the content height is wrong

### ISSUE THREAD

**Issue by Icer2000** [driftyco/ionic#5187]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>1.x</span>

**Platform**: <span ionic-platform>android</span> <span ionic-platform-version>5.1</span>  <span ionic-webview>webview</span>

<span ionic-description>1.Create a screen without header and footer bars
2.Open the keyboard to enter something
=> The height of the content is calculated in the wrong fashion

Code wrong (Original Source code scrollViewNative.js):
scrollViewOffsetHeight = Math.max(0, Math.min(self.__originalContainerHeight, self.__originalContainerHeight - (e.detail.keyboardHeight - 43)));

Code right (Altered Source Code):
scrollViewOffsetHeight = Math.max(0, Math.min(self.__originalContainerHeight, self.__originalContainerHeight - (e.detail.keyboardHeight - ($scope.$hasHeader ? 43 : 0))));

This could of course also be solved in different ways, but this helped me solving the problem.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This looks like the same issue as https://github.com/driftyco/ionic/issues/5800 but im not sure

**Comment by Icer2000** [comment]
Until now i also found out that the problem is still the calculation of the height of the scrollview, but you also need to set the App to fullscreen and set hideKeyboardAccessoryBar(true) .

My problem was fixed because we do not have a Fullscreen App anymore, therefore i can not provide a more detailed problem description.

Regards,
Andre

**Comment by adamdbradley** [comment]
Sounds like it's fixed now, and the upcoming release has a few more fixes. Thanks.

**Comment by m1r4ge** [comment]
@adamdbradley Could you reopen the issue? The problem is still here in v1.3. 
The following formula should probably solve the issue and eliminate the magical number 43.

`scrollViewOffsetHeight = Math.max(0, Math.min(self.__originalContainerHeight, self.__originalContainerHeight - (e.detail.keyboardHeight - (window.innerHeight - rect.bottom))));`

**Comment by EzheG** [comment]
@jgw96 @adamdbradley The bug is still relevant. Check this fix.

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This has been fixed in the latest Ionic 1 release 🎉

**Comment by EzheG** [comment]
@jgw96 No, it's another bug. And it is still there

**Comment by Wvhf** [comment]
Any update for this issue yet ? Still having this issue in Ionic version 1.3.3

**Comment by janpio** [comment]
Ionic v1 lives here now: https://github.com/ionic-team/ionic-v1
