### ISSUE TITLE
bug: Screen goes black after pressing back button

### ISSUE THREAD

**Issue by ihadeed** [driftyco/ionic#5355]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>7</span>  <span ionic-webview>webview</span>

<span ionic-description>I have a side menu type of application ..
When I run it on iOS I get a black screen sometimes when I press the back button. This only happen if I display an alert with an input prior to that.

Displaying an alert with an input always makes the whole screen go black with only the input showing. And sometimes when I tap the back button I get the same black screen again. The only way to get out of it is by swiping from the side to open the side menu and navigate somewhere else.</span>

<span is-issue-template></span>

**Update:** the black screen seem to appear on iPad only.. While testing on iPhone 6s it shows the black background for a moment only.

**Update 2:**
Just had the same issue on Android as well.
I had an Alert with an input open, after closing it and hitting the back button, the screen turned all white. I was was able to get out of the white screen by swiping to open the side menu and navigate out of that page.

**Comment by ihadeed** [comment]
Update: the black screen seem to appear on iPad only..  While testing on iPhone 6s it shows the black background for a moment only.

**Comment by djangojack** [comment]
@ihadeed  Why did you close this issue? I am running beta 3 on an iPhone5 and am occasionally running into the black screen after hitting the back button on a simple sidemenu app. @adamdbradley

**Comment by ihadeed** [comment]
@djangojack I did not test this again, I thought it was fixed...

I will try to reproduce the issue the same way I did before..

**Comment by tskweres** [comment]
I get the black background whenever i have abstract tabs with child views nested 2 deep. And I notice it happens when I navigate back to views with ng-repeats and long lists.

for whatever reason, the 'active' view never receives nav-view="leaving", it goes straight from active to cached.

Any fixes?

**Comment by henrysearle** [comment]
I'm still seeing this. To reproduce, go into any depth of nesting, then click the back button but keep clicking in the same spot. Screen goes black. Looking at the HTML the 'base' screen actually get's removed.

I can repeat it every time now + looking for a work around (I'm thinking to disable the button once it's been clicked).
