### ISSUE TITLE
bug: Swipe to go back swipe to open side menu conflict

### ISSUE THREAD

**Issue by tones411** [driftyco/ionic#5575]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>ios</span> <span ionic-platform-version>9</span>  <span ionic-webview>webview</span>

<span ionic-description>**Steps to reproduce issue:**
1. Run the sidemenu starter template on iOS
2. Expand the side menu and choose "List"
3. Tap a few items to go several levels deep.
4. Swipe from the left to display the sidebar.

**Results:**
1) If you swipe slowly you can see 3 views: the current view, the previous view, and the side menu.
2) If you swipe fast, you don't see the previous view.
3) Either way, after collapsing the sidemenu you are left on the previous view.</span>

<span is-issue-template></span>

**Comment by tones411** [comment]
I am no longer able to reproduce this issue.

**Comment by jgog** [comment]
+1
Here is the demo:
![untitled](https://cloud.githubusercontent.com/assets/971411/13377807/32e0e01c-de11-11e5-8e1e-61a2fb462869.gif)

**Comment by adamdbradley** [comment]
Thanks for reporting the issue, this should be fixed in the next release. Thanks

**Comment by DavidWiesner** [comment]
@adamdbradley It's still an issue in beta.10. Here is a plunkr http://plnkr.co/edit/7FPqi8aoiCzbGUuSAz8a?p=preview

**Comment by HamzaLJ** [comment]
I am experiencing the same issue!!

**Comment by jigs1212** [comment]
Do we have the edge swipe slide menu ?

**Comment by sanjay-sahani** [comment]
I am also experiencing the same issue.
