### ISSUE TITLE
Toggle change event not firing, only click event works

### ISSUE THREAD

**Issue by wanjungao** [driftyco/ionic#5611]
#### Short description of the problem:

Ionic2, toggle element, (change) does not fire, same routing can be triggerred by (click)

#### What behavior are you expecting?

1. change of the ngModel's value should trigger the event
2. provide a way to reference current toggle's value in the change event. 

I had to use click event to trigger routing, and $event's target element does not provide clean way to retrieve the value (it points to html button, not toggle object)

```
      <ion-item>
            <ion-label>wifiLight</ion-label>
            <ion-toggle id="wifiLight" [ngModel]="wifiLight" (click)="patch('wifiLight')"></ion-toggle>
        </ion-item>
```

**Ionic Version**: 2.x

**Browser & Operating System**: iOS / Android / Chrome
IOS

**Comment by isu182** [comment]
I have exactly the same issue, any solution?

**Comment by brandyscarney** [comment]
I'm not seeing this in our 2.0 branch, so it should be fixed in beta.2. Could you test your app against 2.0 and see if you that fixes it? Some steps to test against the 2.0 branch: https://github.com/driftyco/ionic/blob/2.0/scripts/README.md#developing-against-ionic-locally

**Comment by daveshirman** [comment]
I too can report that this is still happening.  No (change) event is firing at all in my toggle.

**Comment by adamdbradley** [comment]
I'm not able to reproduce this with beta2. Would you be able to update and see if it's fixed?

Also, this is the test that I'm using: 
https://github.com/driftyco/ionic/blob/2.0/ionic/components/toggle/test/basic/main.html#L37
https://github.com/driftyco/ionic/blob/2.0/ionic/components/toggle/test/basic/index.ts#L50

**Comment by daveshirman** [comment]
Ok sure, how do I update my local version of ionic from terminal?

Thanks.

**Comment by daveshirman** [comment]
Weird, despite running sudo npm install -g ionic@beta, terminal still says:

ionic-framework            2.0.0-alpha.57  2.0.0-alpha.57  2.0.0-beta.2  myionic2project

i.e. it didn't update the installed version to current.
AND
my package.json still says it's using:
ionic-framework: 2.0.0-alpha.57

Yet, the change event is now firing.

Is this expected? Am I even running the update command correctly?  

Thanks.

**Comment by frederikschubert** [comment]
npm install -g ionic@beta installs/updates the ionic cli and not the local version of the ionic framework.
The change event is not fired when dragging the toggle as opposed to clicking it.

**Comment by wanjungao** [comment]
Still not working. Does it need beta2?

npm install -g ionic@beta results:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Version: 2.0.0-beta.1
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v4.2.4
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by jgw96** [comment]
@wanjungao This bug looks like it was fixed in beta.2 so yes i would recommend testing with beta.2 (:

**Comment by brandyscarney** [comment]
@wanjungao Take a look at our npm docs in order to update the framework version: http://ionicframework.com/docs/v2/resources/using-npm/

Running `npm install -g ionic@beta` is updating the **Ionic CLI Version**. We renamed the npm module from `ionic-framework` to `ionic-angular`, as well, so I'd recommend taking a look at the changelog to see what has changed since beta.1: https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md

**Comment by wanjungao** [comment]
It works with beta3. 

Thanks,

**Comment by brandyscarney** [comment]
Awesome, thanks! :smile:

**Comment by jgw96** [comment]
@wanjungao Glad beta3 fixed your issue!
