### ISSUE TITLE
[v2] ion-item doesn't get 'activated' when it contains html elements

### ISSUE THREAD

**Issue by biesbjerg** [driftyco/ionic#6192]
#### Short description of the problem:
ion-item doesn't get class 'activated' on mousedown when it contains html elements.

#### What behavior are you expecting?
I expected ion-item to get 'activated' (default grey background) when clicked/tapped/mousedown, no matter the contents of ion-item.

**Steps to reproduce:**
1. View plunker: http://plnkr.co/edit/L8MJR6xt6Ddcj09q1ZgV?p=preview
2. Trigger a mousedown event on the text that says "I DON'T WORK" (Text is in an html element)
3. Trigger a mousedown event on the text that says "I DO WORK" and see that it works (Text is direct child of ion-item)

I've traced down the code that is responsible for added 'activated' class to activatable elements. I will attempt creating a pull request shortly.

```
Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
ios-deploy version: 1.8.5
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v4.4.2
Xcode version: Xcode 7.3 Build version 7D175
```

**Comment by biesbjerg** [comment]
This also solves #6159 for me regarding the ignored click events, although I can't explain why.

**Comment by biesbjerg** [comment]
I have a suggestion for optimizing isActivatable():

```
diff --git a/ionic/components/tap-click/tap-click.ts b/ionic/components/tap-click/tap-click.ts
index 8f6a3a1..bb40527 100644
--- a/ionic/components/tap-click/tap-click.ts
+++ b/ionic/components/tap-click/tap-click.ts
@@ -196,13 +196,13 @@ function getActivatableTarget(ele) {
  * @private
  */
 export function isActivatable(ele) {
-  if (ACTIVATABLE_ELEMENTS.test(ele.tagName)) {
+  if (ACTIVATABLE_ELEMENTS.indexOf(ele.tagName)) {
     return true;
   }

   let attributes = ele.attributes;
   for (let i = 0, l = attributes.length; i < l; i++) {
-    if (ACTIVATABLE_ATTRIBUTES.test(attributes[i].name)) {
+    if (ACTIVATABLE_ELEMENTS.indexOf(attributes[i].name.toUpperCase()) !== -1) {
       return true;
     }
   }
@@ -218,8 +218,8 @@ function removeListener(type, listener) {
   document.removeEventListener(type, listener);
 }

-const ACTIVATABLE_ELEMENTS = /^(A|BUTTON)$/;
-const ACTIVATABLE_ATTRIBUTES = /tappable|button/i;
+const ACTIVATABLE_ELEMENTS = ['A', 'BUTTON'];
+const ACTIVATABLE_ATTRIBUTES = ['TAPPABLE', 'BUTTON'];
 const POINTER_TOLERANCE = 4;
 const POINTER_MOVE_UNTIL_CANCEL = 10;
 const DISABLE_NATIVE_CLICK_AMOUNT = 2500;
```
The above changes make the isActivatable() function 3-4x times faster detecting if the element is activatable.

See simple benchmark here: http://dev.infoproducts.dk/ionic/index.html

**Comment by manucorporat** [comment]
@biesbjerg check out my PR: #6205

**Comment by adamdbradley** [comment]
This should be fixed in the next release from this PR: https://github.com/driftyco/ionic/pull/6205 Thanks

**Comment by dtruel** [comment]
This is still not working for me:

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.35
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 7.3 Build version 7D175
