### ISSUE TITLE
App needs es6-shim.map, Reflect.js.map

### ISSUE THREAD

**Issue by dheran** [driftyco/ionic#6925]
Ionic v2
I executed app in android as cordova application. 
and inspected via chrome://inspect and I found below 404 errors
![capture](https://cloud.githubusercontent.com/assets/15922996/16088033/de1b76a0-3342-11e6-9323-fe7b69ff0abe.PNG)

**Comment by jgw96** [comment]
Hello! While we appreciate you opening an issue with us i am going to close this issue and ask that you open a new one that has the issue template filled out please. Thanks for using Ionic!

**Comment by Kobzol** [comment]
Do you have the missing files (es-6shim, reflect) in the main html file?
```html
<body>
  <ion-app></ion-app>

  <script src="cordova.js"></script>
  <script src="build/js/es6-shim.min.js"></script>
  <script src="build/js/Reflect.js"></script>
  <script src="build/js/zone.js"></script>
  <!-- the bundle which is built from the app's source code -->
  <script src="build/js/app.bundle.js"></script>
</body>
```

**Comment by prtku1990** [comment]
can u paste the contents of your package.json file

**Comment by ghenry22** [comment]
it's the .map files that are missing, not the js files themselves. I see exactly the same, it doesn't seem to affect functionality at all but it would be good to note have errors being thrown in the console.

**Comment by jgw96** [comment]
Hello all! This should be fixed with the latest version of the Ionic CLI. To update your ionic CLI you can simply run `npm install -g ionic@beta` (you will probably need sudo on osx/linux). Thanks for using Ionic!

**Comment by dheran** [comment]
issue is still there for Android 4.4 kitkat (chrome 30.0.xx)
