### ISSUE TITLE
Error: No value accessor for 'email' beta10  and @angular/form 0.2.0 rc3

### ISSUE THREAD

**Issue by Anshdesire** [driftyco/ionic#7461]
```
import { Component } from '@angular/core';
import {  REACTIVE_FORM_DIRECTIVES, FormGroup, FormBuilder, Validators } from '@angular/forms';
import { NavController } from 'ionic-angular';
import {FeedPage} from '../feed/feed';

/*
  Generated class for the LoginPage page.

  See http://ionicframework.com/docs/v2/components/#navigation for more info on
  Ionic pages and navigation.
*/
@Component({
  templateUrl: 'build/pages/login/login.html',
  directives: [REACTIVE_FORM_DIRECTIVES],
  providers: [FormBuilder]
})
export class LoginPage {
  loginForm: FormGroup;

  constructor(private nav: NavController, private form_builder: FormBuilder) {
    this.loginForm = this.form_builder.group({
      email: [''], //, emailValidator.mailFormat
      password: ['']
    });
  }

  doLogin(event):void {
    console.log(this.loginForm.value);
  //  if (loginSuccessful) {
      this.nav.setRoot(FeedPage);
  //  }
  event.preventDefault();
 }

}

```

view 

```
<!--
  Generated template for the LoginPage page.

  See http://ionicframework.com/docs/v2/components/#navigation for more info on
  Ionic pages and navigation.
-->
<ion-header>

  <ion-navbar>
    <ion-title>login</ion-title>
  </ion-navbar>

</ion-header>


<ion-content padding>

  <form [formGroup]="loginForm" (submit)="doLogin($event)">
    <ion-list class="loginSection" style="  vertical-align: middle">
      <ion-item [class.error]="!loginForm.controls.email.valid && !loginForm.controls.email.pristine">
        <ion-input type="email" formControlName="email" name="email"></ion-input>
      </ion-item>

      <ion-item [class.error]="!loginForm.controls.password.valid && !loginForm.controls.password.pristine">
        <ion-input type="password" formControlName="password" name="password" placeholder="Password"></ion-input>
      </ion-item>
    </ion-list>

    <button class="login" primary block>Login</button>

  </form>

</ion-content>

```

**Comment by WHarris22** [comment]
I think your issue is related to [this one](https://github.com/driftyco/ionic/issues/7125).

**Comment by Anshdesire** [comment]
@wesleycho - Kind of. Is it resolved , as i have already seen and tried many things but failed to achieve solution ?

**Comment by WHarris22** [comment]
It is closed so yes it is resolved. 

You will need to install the nightly version though so you have a version of the framework that contains this fix.

**Comment by jgw96** [comment]
Hello all! I will be closing this issue as a duplicate of #7125 . Thanks for using Ionic!

**Comment by Anshdesire** [comment]
@WHarris22, @jgw96   - still not able to get solution :( let me know the steps :(

**Comment by Anshdesire** [comment]
now can use in rc11 which supports rc4
