### ISSUE TITLE
Beta 11 bug: "No provider for..." app.ts providers not visible to page in modal controller

### ISSUE THREAD

**Issue by thomaswb** [driftyco/ionic#7592]
#### Short description of the problem:

In beta 10 and earlier, any provider defined in app.ts could be used as a singleton provider in any pages, whether on the normal navigation stack or when presented in a modal controller.

In beta 11, the page in the modal throws an exception:

```
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in ./SignInPage class SignInPage_Host - inline template:0:0
ORIGINAL EXCEPTION: No provider for SessionService!
```

As expected, adding SessionService as a provider removes the exception, but generates a new instance of SessionService instead of using the app singleton, so a successful login is not usable by the app.

#### What behavior are you expecting?

All components, whether in the normal nav stack or inside modals, should have access to the app's providers.

**Steps to reproduce:**
 
app.ts:
```
import {SessionService} from './providers/session-service/session-service';
@Component({
  templateUrl: 'build/app.html', providers: [SessionService]
})
```

home.ts:
```
this.modalController.create(SignInPage).present();
```

sign-in.ts:
```
import {SessionService} from '../../providers/session-service/session-service';
@Component({
  templateUrl: 'build/pages/sign-in/sign-in.html'
})
constructor(private sessionService:SessionService) {...}
```
**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.11

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

Cordova CLI: 6.3.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0-beta.36
Ionic App Lib Version: 2.0.0-beta.19
ios-deploy version: 1.8.3 
ios-sim version: 5.0.4 
OS: Mac OS X El Capitan
Node Version: v4.2.2
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by ValterSantosMatos** [comment]
I have the same

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Would you mind putting your `providers` array into your `ionicBootstrap()` ? This should fix the issue for you. Here is an example: 
```
ionicBootstrap(MyApp, [SessionService]);
```

**Comment by szerner** [comment]
@jgw96 For me that works. Since beta.11 I had problems ("No provider for...") with a service (ng-translate) I registered in the [providers] property of my app.ts. I moved it to ionicBootstrap as you suggested and now my popovers have access to that service again. Perhaps it should be mentioned in the beta.11 upgrade instructions.

**Comment by thomaswb** [comment]
Thanks, I'd forgotten about the bootstrap. That does indeed solve the "no provider" error, but it doesn't fix the real problem-- which is that the app.ts providers are no longer singletons. 

In beta 10, defining a provider in app.ts created a singleton SessionService object that could be used in all components and pages just by adding it as a private parameter in the constructor. In beta 11, adding it in the constructor gives a **NEW** instance, which is useless. I'd hate to have to use a global variable for my session!

**Comment by thomaswb** [comment]
Ah, correction. I hadn't removed SessionService from the app.ts providers. I've now done that, and I have a singleton again.

Sorry for the noise.

**Comment by jgw96** [comment]
@thomaswb No problem! Glad that fixed it for you. Thanks for using Ionic!

**Comment by tgangso** [comment]
ionViewDidEnter does also fire when dismissing a modal now, it did not do that before

**Comment by mordka** [comment]
I'm still experiencing an issue with services not being singleton. 
I'm opening a modal page which has a `FilterService` injected. The service is specified in top level providers like that: 
```ionicBootstrap(MyApp, [FilterService]);```
I'm sure it's not put as a provider in any other component. When the modal is opened, then FilterService instance is created, when it shouldn't.

In beta.10 this worked really good, all services in ionicBootstrap were singletons. After upgrading to beta.11 and using `ModalController` to open modal - it doesn't work. 

For now I have to downgrade the app to beta.10.

**Comment by arsindelve** [comment]
I am experiencing the problem @mordka reports above. Components seem to get a new instance of a service which is registered using ionicBootstrap. This is happening in beta 11. I don't seem to be able to get a singleton service shared across all my components no matter what I do.

**Comment by ValentinPrototype** [comment]
@arsindelve Could it be that you inject your service in the decorator?

```typescript
import { FooService } from '../shared/foo.service';

@Component({
  providers: [FooService] // This creates a new instance even if FooService is global, leave that out
})
export class MyModal {
  constructor(private fooService: FooService) { }
}
```

**Comment by arsindelve** [comment]
@ValentinPrototype I don't believe so, no. I am injecting it as mordka describes above, only in the bootstrap and nowhere else.

**Comment by awe-sim** [comment]
Hi,

I'm facing the same issue. Here's my `ionic info`:

    Your system information:
    Cordova CLI: 6.4.0
    Ionic Framework Version: 2.0.0-rc.3
    Ionic CLI Version: 2.1.14
    Ionic App Lib Version: 2.1.7
    Ionic App Scripts Version: 0.0.46
    ios-deploy version: Not installed
    ios-sim version: Not installed
    OS: macOS Sierra
    Node Version: v6.9.1
    Xcode version: Not installed

If I include my service in `app.component.ts` as follows, it gives me an error `No provider for MyService` when I load the modal view.

    @Component({
      templateUrl: 'app.html',
      providers: [ MyService ],
    })

If I revert `app.components.ts` back the way it was and include my service in `main.dev.ts` as follows, it gives me the same error right when the application is loaded:

    platformBrowserDynamic().bootstrapModule(AppModule, {
      providers: [ MyService ]
    });

Is there any update on this?

**Comment by rich25200** [comment]
Hi @awe-sim ,

You need include your service in app.module.ts and your service will be  available in all your app.

**Comment by sebastianovide** [comment]
hi @rich25200 , 

I've added to app.module.ts (in the providers array) but I still getting ORIGINAL EXCEPTION: No provider for MyService!

any ideas ?

**Comment by rich25200** [comment]
hi @sebastianovide ,

Did you import your service and inject  it in the constructor?
