### ISSUE TITLE
ionic2 - bug?(popover) - navigation from popover.

### ISSUE THREAD

**Issue by zakton5** [driftyco/ionic#8218]
#### Short description of the problem:
This is kind of a question, but could also be a bug/enhancement. If I open a popover, say on a details page, it has options to Edit or Delete the item. When I delete the item, I want to pop the detail page off of the stack. However, this does not work from within the popover. Instead, I have to use Events or pass callbacks.

On the other hand, I am able to push a page onto the navstack, but only in a very certain way.

So, is there, or could there be, any way to accomplish this, or do I have to keep using Events, which I respond to on the detail page itself?

**Comment by ekhmoi** [comment]
dont you mind to share your code showing the problem ?

**Comment by zakton5** [comment]
Sure, there isn't much to it. Within a popover component:

```ts
this.viewCtrl.dismiss().then(() => {
    this.navCtrl.pop();
});
```

This code successfully dismisses the popover, but does not navigate back. However, the following code sucessfully navigates forward:

```ts
this.viewCtrl.dismiss().then(() => {
    this.navCtrl.push(Page);
});
```

**Comment by jgw96** [comment]
Hello @zakton5 thanks for opening an issue with us! This has been fixed in the rc.0 release. Thanks for using Ionic!

**Comment by florianbepunkt** [comment]
This issues has not been fixed: 

this.viewCtrl.dismiss().then(() => {
    this.navCtrl.pop();
});

Still does not navigate back, it only dismisses the popover. I have exactly same situation as @ekhmoi described

Instead of navigating back it throws an errror message

> polyfills.js:3 Unhandled Promise rejection: Cannot read property 'getTransitionName' of null ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property 'getTransitionName' of null(…) TypeError: Cannot read property 'getTransitionName' of null

**Comment by tetpsy** [comment]
Hi there, might be way too late but i figured this out by using the App import on my popover page.

import { App } from 'ionic-angular';

constructor(public appCtrl: App) {}

this.appCtrl.getRootNav().pop();
