### ISSUE TITLE
Ionic2 RC0 - Android (MD) SearchBar cancel button missing

### ISSUE THREAD

**Issue by oborudko** [driftyco/ionic#8403]
After upgrading to RC0, the searchbar for material design stopped showing the back button on the left, where it was replacing the search icon and triggering (ionCancel). It works fine on iOS, just not working on android.

        <ion-searchbar [hidden]="!searchMode" showCancelButton="true"
                       [(ngModel)]="queryText"
                       (ionInput)="updateSchedule()"
                       (ionCancel)="toggleSearch()"
                       placeholder="Search">
        </ion-searchbar>

IOS:
![screen shot 2016-10-02 at 10 46 28](https://cloud.githubusercontent.com/assets/3165152/19020279/713ada08-889c-11e6-8fec-5b76b97f79b5.png)

MD:
![screen shot 2016-10-02 at 10 46 03](https://cloud.githubusercontent.com/assets/3165152/19020280/79eb40b6-889c-11e6-827f-5478b4e5c2b0.png)

As I said it used to work before RC0, showing something like this on MD:

![screen shot 2016-10-02 at 10 50 25](https://cloud.githubusercontent.com/assets/3165152/19020281/7ec4b914-889c-11e6-847c-2a82358dab86.png)

Thanks.

**Comment by dudeofawesome** [comment]
Is there a good way to get this fix before rc1 is released?

**Comment by cleever** [comment]
Why this issue is closed?
The problem still happens in rc1.

**Comment by dudeofawesome** [comment]
This issue does not seem to have been fixed in rc1 for me either. @manucorporat

**Comment by richardmarais** [comment]
I still get this issue with:

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.3.0
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v6.9.4
Xcode version: Xcode 8.3 Build version 8E162
```

Works fine in iOS, but Android `[showCancelButton]="true"` does not display the cancel button.
