### ISSUE TITLE
iOS Momentum scrolling issue with input fields

### ISSUE THREAD

**Issue by skill83** [driftyco/ionic#8503]
#### Short description of the problem:

When you have a page with an ion-list and multiple ion-item with ion-input inside, on ios the scrolling is flickering
#### What behavior are you expecting?

The scrolling should be fine

**Steps to reproduce:**
1. Create a simple ionic app
2. Add a new page
3. Use the provided code for the page
4. Build it and run on ios device

```
<ion-header class="add-event-page">
  <ion-navbar></ion-navbar>
</ion-header>
<ion-content no-padding="no-padding" class="add-event-page">
  <ion-list>
    <ion-item>
      <ion-label>Label 1</ion-label>
      <ion-input placeholder="input 1"></ion-input>
    </ion-item>
    <ion-item>
      <ion-label>Label 2</ion-label>
      <ion-input placeholder="input 2"></ion-input>
    </ion-item>
  </ion-list>
</ion-content>
```

[video_of_the_bug.zip](https://github.com/driftyco/ionic/files/510362/video_of_the_bug.zip)

BUG
![bug](https://cloud.githubusercontent.com/assets/656011/19189859/7a641ef8-8c9a-11e6-9e5c-1e808b836c3a.gif)

NOBUG
![nobug](https://cloud.githubusercontent.com/assets/656011/19189868/8331d17e-8c9a-11e6-83fc-30886dbbfeec.gif)

**Other information:** 
if you have just a single input the issue is not showing

**Which Ionic Version?** 
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.0
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.1.0-beta.1
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v6.7.0
Xcode version: Xcode 8.0 Build version 8A218a

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! Does this still happen with [our wkwebview plugin](https://github.com/driftyco/cordova-plugin-wkwebview-engine#installation-instructions)?

**Comment by skill83** [comment]
Hi, thanks for the answer;
i just tried to use the plugin, but the app is crashing just after launching and xcode console is telling
```
TestApp(2985,0x1b8bc2c40) malloc: *** error for object 0x1740ab460: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

**Comment by jgw96** [comment]
@skill83 The above error should be fixed in the latest version of the plugin, mind trying again? Thanks!

**Comment by skill83** [comment]
@jgw96 it seems almost solved...  i mean in some pages it's still presenting the issue.
Anyway now i cannot debug anymore the app with safari because every time i try to inspect, the app crash.

**Comment by jgw96** [comment]
@skill83 Sorry about that! Would you mind posting an issue about this on the [wkwebview repo](https://github.com/driftyco/cordova-plugin-wkwebview-engine) ?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
