### ISSUE TITLE
bug: Page pushed from root page causes it to be blank

### ISSUE THREAD

**Issue by ThorConzales** [driftyco/ionic#8510]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.0.0 RC0</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When a new page is pushed from the root page's ionViewDidEnter event  in app startup then the new page is entirely blank.This is a desired behavior because I prefer this approach over switching root page in navController to switch between pages which might work better. ionViewDidEnter event is used because I assumed it is the last event in the initialization stack. When this call is wrapped inside a timeout delaying the action at least half a second then it works properly so it seems that not everything is properly set up when the ionViewDidEnter event hits. I also tried ionViewLoaded event but it yields the same result.

Here is a demo project: https://drive.google.com/open?id=0BxT1AJ0A_TYORXQ3YXJxNXNkQUE

Code if you don't want to download the project, put it into your root page:
```
public ionViewDidEnter() {
        this.navController.push(AboutPage);
        //Setting it in timeout will work but it is also causing race condition which is not guaranteed to finish in correct order.
        //setTimeout(() => this.navController.push(AboutPage), 1000);
    }
```
</span>

<span is-issue-template></span>

**Comment by candelibas** [comment]
Any progress?

**Comment by manucorporat** [comment]
@ThorConzales this bug was already fixed. I just added a new e2e test to verify it!

**Comment by trinhvanhuy** [comment]
Hello @manucorporat 
I saw thats it's fixed, how can i get that fix ? Just download src from github and replace with mine ?

**Comment by ThorConzales** [comment]
Still reproducible with RC1 release.

**Comment by manucorporat** [comment]
@ThorConzales ok, I think now it is fixed here: https://github.com/driftyco/ionic/commit/ba557acb4fbad8040f7cd4e5f537901729197ca5

I am working in new unit tests and asserts across the whole framework to prevent this kind of bugs happen again

**Comment by Gp2mv3** [comment]
I still have the exact same issue with Ionic RC2.
The page has an opacity: 0 as show-page is not happened to the class.

**Comment by Cendrao** [comment]
I still have the issue too using Ionic 2.1.17.

I have this issue on Android, never tried on iOS
