### ISSUE TITLE
[RC0] Regression: Presenting Alert or ActionSheet destroys Modal

### ISSUE THREAD

**Issue by alex-pl** [driftyco/ionic#8573]
Creating and presenting an `Alert` or `ActionSheet` inside of a `Modal` destroys the modal. The modals callback isn't called and the hide animation isn't played either. The alert or action sheet is not displayed.

Version: Ionic 2 rc0

### Modal

_modal.ts_

```TypeScript
import { Component } from '@angular/core';
import { AlertController } from 'ionic-angular';

@Component({
    templateUrl: 'modal.html'
})
export class Modal {

    constructor(private alertController: AlertController) { }

    public ionViewDidEnter() {
        let alert = this.alertController.create({
            title: 'Test',
            buttons: [
                {
                    text: 'Something',
                    role: 'cancel'
                }
            ]
        });
        alert.present();
    }

}
```

_modal.html_

```HTML
<ion-content>Hello :)</ion-content>
```

### Page

_page.ts_

```TypeScript
import { Component } from '@angular/core';
import { ModalController } from 'ionic-angular';
import { Modal } from '../modal';

@Component({
    templateUrl: 'page.html'
})
export class Page {

    constructor(private modalController: ModalController) { }

    open() {
        let modal = this.modalController.create(Modal);

        modal.onDidDismiss(() => {
            console.log('callback');
        });

        modal.present();
    }

}
```

_page.html_

```HTML
<ion-header>
    <ion-navbar>
        <ion-title>Test</ion-title>
    </ion-navbar>
</ion-header>

<ion-content>
    <button ion-button (click)="open()">Show Modal</button>
</ion-content>
```

**Comment by manucorporat** [comment]
@alex-pl I can not reproduce this bug with the provided source code.
can you create a repo that reproduces the issue?

**Comment by alex-pl** [comment]
Sorry for the delay, I've created a repository now:
https://github.com/alex-pl/ionic-modal-alert-issue

The test case is based on the _tutorial_ template:
```
ionic start ionic-modal-alert-issue tutorial --v2
```

I've committed every step and added a short readme to make it as clear as possible.
Thanks for looking into it!

**Comment by manucorporat** [comment]
ok, this was already fixed in RC1!

**Comment by alex-pl** [comment]
Awesome, thanks! 👍

**Comment by erperejildo** [comment]
guys I'm using Ionic 3 and I still having this issue. Do I need to change any configuration?
