### ISSUE TITLE
Pollyfills Unhandled Promise rejection: Failed to load *.html

### ISSUE THREAD

**Issue by jhonny9550** [driftyco/ionic#8711]
I have and issue with new version of ionic 2 when y try to change a screen with `navCtrl.push();`

Error:
![image](https://cloud.githubusercontent.com/assets/17908642/19402152/0e1ccba6-9225-11e6-9ce9-95d8706d0ff5.png)

My .Ts:

```
import { Component } from '@angular/core';
import { NavController,NavParams,AlertController } from 'ionic-angular';
import {Http,Headers, RequestOptions} from '@angular/http';

@Component({
  selector: 'page-signup',
  templateUrl: 'signup.html'
})
export class Signup {

  constructor(public navCtrl: NavController,public alertCtrl:AlertController,public http:Http) {}

  OnLegals(){
    this.navCtrl.push(Legals);
  }

  ionViewDidLoad() {
    console.log('Hello Signup Page');
  }

}

@Component({
  selector: 'page-legals',
  templateUrl: 'legals.html'
})
export class Legals {

}

@Component({
  selector:'page-message',
  templateUrl:'welcomeMsg.html'
})
export class WelcomeMsg {
  email:string;
  constructor(public navCtrl:NavController,public params: NavParams){}
  OnNext(){
    this.email = this.params.data.correo;
  }
}
```

And this is my module.Ts:

```
import { NgModule } from '@angular/core';
import { IonicApp, IonicModule } from 'ionic-angular';
import { MyApp } from './app.component';
import { AboutPage } from '../pages/about/about';
import { ContactPage } from '../pages/contact/contact';
import { HomePage } from '../pages/home/home';
import { TabsPage } from '../pages/tabs/tabs';
import {Welcome} from '../pages/welcome/welcome';
import {Login} from '../pages/login/login';
import {Signup} from '../pages/signup/signup';
import {Automotores} from '../pages/automotores/automotores';
import {Legals} from '../pages/signup/signup';

@NgModule({
  declarations: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage,
    Welcome,
    Login,
    Signup,
    Automotores,
    Legals
  ],
  imports: [
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    AboutPage,
    ContactPage,
    HomePage,
    TabsPage,
    Welcome,
    Login,
    Signup,
    Automotores,
    Legals
  ],
  providers: []
})
export class AppModule {}
```

Some answer pls? I'll thank you a lot.

**Comment by morrisonbrett** [comment]
Cross referencing here: https://forum.ionicframework.com/t/polyfills-failed-to-load-html-rc0/64949

Having the same issue.  Not for all pages - just some - and even with logic of the .TS and .HTML commented out, I'm still seeing it.

**Comment by mweimerskirch** [comment]
I had the same error after upgrading from RC0 to RC1. I had multiple components in one ts file. After splitting them up into one file each, the "unhandled promise rejection" error was gone.

**Comment by jgw96** [comment]
Hello all! Thanks for using Ionic! This has been fixed in the latest iteration of `ionic-app-scripts`. To update just run `npm install @ionic/app-scripts@latest --save-dev`.

**Comment by Umasankar512** [comment]
I am not using Ionic!! I am still getting same error. Can anyone help?

**Comment by daveleslie** [comment]
try using the absolute path to your templateUrl

**Comment by domantasjurkus** [comment]
`yas`
