### ISSUE TITLE
bug: White screen on pressing nav-back-button

### ISSUE THREAD

**Issue by stevengunneweg** [driftyco/ionic#8976]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>When quickly pressing the default back button on a pushed view multiple times the app gets into a blank-screen. The same happens when you do nav.pop() while you are in the root page.</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! This has already been fixed in master and will be in the rc2 release.

**Comment by stevengunneweg** [comment]
Thanks for your reply. However with RC2 I can still reproduce this issue rather easily.
I'm using ionic-angular@2.0.0-rc.2 and app-scripts@0.0.42.
The issue is visible on both Android and iOS.

**Comment by matheusdavidson** [comment]
i'm having the same issue, ```this.nav.pop()``` leads to white screen. No errors, the page just doesn't load.

**Comment by matheusdavidson** [comment]
@jgw96 this is still happening in the latest version.

**Comment by matheusdavidson** [comment]
Looks like ```pop()``` only works when you enter the route via ```push()```.
I have the white screen problem when i set the route with ```setRoot()``` and try to go back with ```pop()```, but if i enter the route with ```push()``` i can go back using ```pop()```, is this the desired behavior? @jgw96

**Comment by narayana1240** [comment]
i have the same issue but i used   this.platform.exitApp(); in device back button event for app after that when i open the app again i am unable to open it i am getting the error in inspector as below picture

![image](https://user-images.githubusercontent.com/22906946/39045191-d2602d3a-44af-11e8-8627-52f7db1541d3.png)
and below is my system information and plugin information
![image](https://user-images.githubusercontent.com/22906946/39045362-5f373442-44b0-11e8-8923-dfbee1c8bba5.png)
Plugin information that i used in development are:

![image](https://user-images.githubusercontent.com/22906946/39045464-9e0f7f76-44b0-11e8-94bb-7899294303b0.png)

please help me to raid out of this issue
it is happening when i did back button app exit in very initial tinme of the app
