### ISSUE TITLE
Ionic 2 nightly-build - IOS Keyboard popup too slowly

### ISSUE THREAD

**Issue by peterpeterparker** [driftyco/ionic#9602]
I build a test version of my Ionic 2 app within the nightly-build 2.0.0-rc.3-201612100458, mostly because I was interested in the fix https://github.com/driftyco/ionic/issues/8185

I have now sent this version to my test user and they confirm that the use of the keyboard is now improved aka the keyboard doesn't stay open anymore on iOS 10.0, thx of lot for the improvement.

But, they report that when they want to open for the very first time their keyboard from an input field, it took something like 2-3 seconds before the keyboard really opened itself, which is quite a long time on a modern phone. They noticed that behavior on their iPhone 6 / iOS 10. 

My app is still based on UIWebView.

I tried the same behavior on my Nexus 5X with XWalk, didn't faced that lag, the keyboard went open super fast as it should. I tried then on an iPhone 4, there it took like 3-4 seconds.

Is there a way to improve this bad performance? I hope so...

Thx in advance

**Comment by dylanvdmerwe** [comment]
I think pretty much everything on an iPhone 4 will be slow... #justsaying

**Comment by peterpeterparker** [comment]
@dylanvdmerwe I added the iPhone4 for comparison purpose, just to say that the ratio isn't that big between the iPhone4 and 6. But the lag of 2-3 to open the keyboard is on a modern device, the 6...

**Comment by peterpeterparker** [comment]
I spoke with my test users again and if I understand correctly, the problem may be related to load of the keyboard in case of ion-input of type="tel"

**Comment by jgw96** [comment]
@peterpeterparker Hello, thanks for the info! So, just so i understand the issue, this is specific to tel type inputs correct? Are you seeing the same issues on your device?

**Comment by peterpeterparker** [comment]
@jgw96 thx for your answer! I clear these questions and ask my tester for some more informations and comeback to you asap.

**Comment by peterpeterparker** [comment]
@jgw96 I spoke with the tester, we made some tests, closing the app, running it again, open, close, keyboard, specific to tel inputs and not tel inputs etc. and finally it turned out that it was now ... ok aka fast enough.

so my guess is, that the keyboard was slow when the app was started from Testflight or after it was reinstalled for the very first time, or something like that. 

I don't own by myself an iPhone 6 or 7, so in the next days, I gonna try to confirm that with some other users.

I own an iPhone 4, but as mentioned by @dylanvdmerwe, of course I can't except the same performance there, even if I would be happy to have something faster there too.

On my Nexus 5X with XWalk, as already mentioned, it works like a charm.

**Comment by jgw96** [comment]
Sounds good! I cant wait to get the confirmation from your users. Really appreciate all the testing!

**Comment by peterpeterparker** [comment]
@jgw96 I met today another person with an iPhone 7 and we achieved, I think, to reproduce the same behavior...but actually, after many tries, I figured out, that there is actually no strictly technical bugs regarding the opening time of the keyboard on iOS 10. The response time was fine.

But, since my friend today and my tester both met the same problem, a kind of misunderstood from the users regarding the ion-label of type stacked. See screenshots, the users tend to click on the upper part of the label which actually doesn't trigger any opening of the keyboard, which gave them the feeling that the keyboard doesn't open or wait for many clicks before open ... which explain why they reported that the keyboard is too slow to open ... Sherlock Holmes here ... 

what do you think, is there any way to make an improvement? of course I would understand if you close that issue.

thx for taking the time having a look here

            <ion-item>
                <ion-label stacked>
                    {{'PRICE' | translate}}
                </ion-label>
                <ion-input type="tel" [(ngModel)]="price" formControlName="priceValidator"></ion-input>
            </ion-item>

<img width="204" alt="capture d ecran 2016-12-14 a 18 48 40" src="https://cloud.githubusercontent.com/assets/16886711/21194236/7a3e4a0a-c22f-11e6-8bdb-4ff36fadb01d.png">

**Comment by jgw96** [comment]
Ahh, good investigating! So yeah, we could probably make a change here to where tapping the label actually focuses the input. Im gonna mark this issue as an enhancement. Thanks!

**Comment by jgw96** [comment]
Actually, this has already been fixed in master with this PR https://github.com/driftyco/ionic/pull/9560 🎉  Going to close this issue for now.

**Comment by peterpeterparker** [comment]
thx for your answer and check of solution @jgw96 !

unfortunately, the PR #9560 doesn't enhance my solution, the ion-label stacked in following code still doesn't trigger the keyboard opening

    <ion-item>
            <ion-label stacked>
                {{'PRICE' | translate}}
            </ion-label>
            <ion-input type="tel" [(ngModel)]="price" formControlName="priceValidator"></ion-input>
        </ion-item>

do I miss something? or should I create a new task?

thx in advance for your feedback

**Comment by peterpeterparker** [comment]
@jgw96 just for the record, I spent the night trying other types of input fields or setting the focus manually (like https://forum.ionicframework.com/t/setting-focus-to-an-input-in-ionic-2/62789/4) but nothing working really properly on iOS 10 (in best case, setting manually focus on iOS 10, the focus is set, the keyboard open and close itself straight away) 

Since one of the core function of my app is a wizard, I would be really happy if you could provide me any tips, anything, open to any idea...thx in advance

**Comment by peterpeterparker** [comment]
For the record, I implemented a scss work around to display the stacked label the same color as the background not the input field. doesn't look pretty good everywhere in my app but at least, give the user the feeling, he can't click there

![screenshot_20161215-082423](https://cloud.githubusercontent.com/assets/16886711/21215276/74a04a3c-c2a0-11e6-9518-f975326fac96.png)
