### ISSUE TITLE
Ionic 2: Slide menu slide in gesture doesn't disable page scrolling underneath

### ISSUE THREAD

**Issue by daveshirman** [driftyco/ionic#9633]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x] **2.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
Slide in the menu from the edge, scrolling in page underneath still possible before you lift your finger off the screen

![shamunbd90zdaveshirman12142016115047](https://cloud.githubusercontent.com/assets/14280030/21181091/1936f97c-c1f4-11e6-8491-5a04ded781d8.gif)

**Expected behavior:**
Slide menu opening should immediately disable scrolling on page underneath.

**Steps to reproduce:**
1. Make a long enough page to require scrolling.
2. Add a side menu.
3. Slide the menu in partially and try to scroll up or down at the same time.
4. Observe page underneath scrolling when it shouldn't.

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Davids-MacBook-Air:apphazard-app daveshirman$ ionic info

Your system information:

Cordova CLI: 6.2.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.12
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: OS X El Capitan
Node Version: v4.3.0
Xcode version: Xcode 8.1 Build version 8B62
```

**Comment by jtushar53** [comment]
Hi @daveshirman 
sorry for out of topic, can you please tell me what do you use to make gif

**Comment by daveshirman** [comment]
Download AndroidTool for Mac. Don't know if it's available for Windows.
Super useful.

**Comment by brandyscarney** [comment]
@daveshirman Could you try using the nightly version of the framework and let me know if you still have this issue? I couldn't reproduce it using nightly. To install nightly:

```
npm install --save ionic-angular@nightly
```

This will also require an update to Angular 2.2.1, see: https://github.com/driftyco/ionic-conference-app/blob/master/package.json#L13

Thanks :)

**Comment by jgw96** [comment]
@daveshirman Hey! We released that latest nightly brandy mentions above as [RC4 today](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md#200-rc4-2016-12-15) so if you update to RC4 you will get the same fixes. I also cannot reproduce this issue with RC4.

**Comment by ronanjia** [comment]
Hey, same problem!
I clone the "ionic-conference-app" project today, and everything works fine, but when i start a "blank" or a "sidemenu" project, the problem remains.
Here is some of my packages info, did i got anything wrong?

```
 "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@ionic/storage": "1.1.6",
    "ionic-angular": "2.0.0-rc.4",
    "ionic-native": "2.2.11",
    "ionicons": "3.0.0",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.47",
    "typescript": "2.0.9"
  }
```


```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.4
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.47
ios-deploy version: 1.9.0 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v6.9.1
Xcode version: Xcode 8.2 Build version 8C38
```

**Comment by daveshirman** [comment]
@jgw96 This is still an issue on 2.0.0 final. Can we get an update please?

**Comment by ronanjia** [comment]
Hi, everyone, i think the problem has been located. Comparing to your "**ionic-conference-app**" which works fine,  project created by "ionic start 'projectName' --v2" use default webView engine which i think is outdated for IOS 9+(may be),  while "**ionic-conference-app**" use new webView engine "**[cordova-plugin-wkwebview-engine](https://github.com/driftyco/cordova-plugin-wkwebview-engine)**" (which i'm not sure is ready for public use)
So, use new webView engine, lots of bugs in iOS could be solved. 
@daveshirman please compare "config.xml" file in your project file to that in "ionic-conference-app" project for details. Change your "config.xml", then Re-Add iOS platform could make your app work.

By the way, @brandyscarney @jgw96 is "cordova-plugin-wkwebview-engine" ready for commercial use?

**Comment by daveshirman** [comment]
@adamdbradley The team has been super silent with many of these outstanding issues and they need addressing. Any updates please?

**Comment by jgw96** [comment]
Hello all! Sorry for the delay on this one. So their is kind of a long story behind this issue. So UiWebView which is the default webview for cordova-ios at the moment has broken scroll events. It also has some interesting flickering issues when changing certain css properties. Because of these two issues we are unable to disable scrolling on UiWebView while opening or closing a sidemenu without causing a massive flicker and we made the decision that being able to scroll while swiping on UIWebView was better than having a huge flicker. Apple has since released a new webview (WkWebView) and while it still has the same flickering issue (although scroll events work great now) we were able to do a fix on the cordova side of things in [our fork of the wkwebview plugin](https://github.com/driftyco/cordova-plugin-wkwebview-engine) that fixes this issue without causing a flicker. For a while we were not ready to push the wkwebview plugin because it had some weird issues but we are not at a state with it that we are ready to start pushing it for production use and in fact we are planning on making it the default iOS webview in the next Ionic release. Because of all this I am going to close this issue now and recommend that https://github.com/driftyco/cordova-plugin-wkwebview-engine be used as the fix. Thanks everyone and again, very sorry for the delay on this.

**Comment by lincolnthree** [comment]
Hey. Just an update. I installed the wkwebview plugin, and while the functionality is improved, it still allows scrolling while initially opening the menu. Once scroll has occurred, it locks as expected, but this is still a problem.

**Comment by brandyscarney** [comment]
@lincolnthree The link in Justin's comment was outdated. I updated it, could you try the new instructions here and let me know if you are still having the issue? https://ionicframework.com/docs/wkwebview/#upgrading-to-wkwebview-uiwebview-users-only

Thanks :)

**Comment by lincolnthree** [comment]
Hey @brandyscarney - I've done all that, and these are the issues I'm seeing:

https://www.youtube.com/watch?v=K_vBD6IJdpE

List of issues visible in this video, with time references:

**0:03** -  If the menu is opened while a page is loading (by setting the rootPage attribute in app.component.xml), then opening the menu (via this.menuCtrl.open()), the menu appears first, then the page slides out overtop of it. I can probably work around this last issue via some creative timing (or possibly using NavController.setRoot(), but it seems a bit odd. 

**0:05** -  While the menu is open, the content view can be scrolled, then once the scroll has completed (**0:11**), it locks down and can no longer be scrolled.

**0:12** - Some odd behavior with swipe gesture. The menu doesn't initially follow the swipe (presumably because the user was swiping up, first). It then, however, recognizes the swipe after the user has released the screen, and snaps closed.

**0:20** - The content view can be scrolled, again. Once scrolled, it stops being scrollable (as it should be from the start (**0:22**)) 

WKWebView is definitely an improvement for this behavior, since prior to upgrading, the content view was *always* scrollable, and now it's just *sometimes* scrollable, but still not quite right.

Any thoughts? Thanks.
